(function(global){
"use strict";

const HOVER_OPEN_MS=320,HOVER_CLOSE_MS=150,DOUBLE_TAP_MS=320;
const MODEL_VERSION="copa-model-v1";
const DIMENSION_KEYS=["impact","build_up","space_control","duels","engine","pressure_decision"];
const bound=new WeakMap(),normalizedCache=new Map(),replaying=new WeakSet();
let root=null,panel=null,openTimer=0,closeTimer=0,requestId=0,current=null,lastTap=null;
let dragging=false,dragSuppressUntil=0,historyPushed=false,previousFocus=null;

const copy={
  tr:{open:"Oyuncu profilini aç",close:"Oyuncu profilini kapat",age:"yaş",club:"Kulüp",country:"Milli Takım Seviyesi",foot:"Kullandığı ayak",positions:"Yan Mevkiler",overview:"COPA PUANLARI",playStyle:"OYUN ROLÜ",strengths:"GÜÇLÜ YÖNLER",risks:"OYUN RİSKLERİ",tendencies:"OYUN EĞİLİMLERİ",analysis:"KISA ANALİZ",loading:"copa.life oyuncu modeli yükleniyor…",noModel:"Bu oyuncu için copa.life oyun modeli bulunamadı.",loadError:"Oyuncu modeli şu anda yüklenemedi.",retry:"Yeniden dene",positionFit:"Mevki Uyumu",modelNote:"copa.life oyun modeli · 0–100",impact:"Hücum Etkisi",keeperImpact:"Kurtarış Etkisi",build_up:"Oyun Kurulumu",space_control:"Alan Kontrolü",duels:"İkili Mücadele",engine:"Tempo ve Dayanıklılık",pressure_decision:"Baskı ve Karar"},
  en:{open:"Open player profile",close:"Close player profile",age:"years old",club:"Club",country:"National Team Level",foot:"Preferred foot",positions:"Secondary Positions",overview:"COPA SCORES",playStyle:"GAME ROLE",strengths:"STRENGTHS",risks:"GAME RISKS",tendencies:"GAME TENDENCIES",analysis:"QUICK ANALYSIS",loading:"Loading the copa.life player model…",noModel:"The copa.life game model is not available for this player.",loadError:"The player model could not be loaded.",retry:"Try again",positionFit:"Position Fit",modelNote:"copa.life game model · 0–100",impact:"Attacking Impact",keeperImpact:"Saving Impact",build_up:"Build-up",space_control:"Space Control",duels:"Duels",engine:"Tempo and Endurance",pressure_decision:"Pressure and Decisions"},
  es:{open:"Abrir perfil",close:"Cerrar perfil",age:"años",club:"Club",country:"Nivel de selección",foot:"Pie preferido",positions:"Posiciones secundarias",overview:"PUNTOS COPA",playStyle:"ROL DE JUEGO",strengths:"FORTALEZAS",risks:"RIESGOS DE JUEGO",tendencies:"TENDENCIAS",analysis:"ANÁLISIS",loading:"Cargando el modelo copa.life…",noModel:"El modelo copa.life no está disponible para este jugador.",loadError:"No se pudo cargar el modelo.",retry:"Reintentar",positionFit:"Encaje posicional",modelNote:"modelo de juego copa.life · 0–100",impact:"Impacto ofensivo",keeperImpact:"Impacto de paradas",build_up:"Construcción",space_control:"Control de espacios",duels:"Duelos",engine:"Ritmo y resistencia",pressure_decision:"Presión y decisiones"},
  de:{open:"Spielerprofil öffnen",close:"Spielerprofil schließen",age:"Jahre",club:"Verein",country:"Nationalteam-Stufe",foot:"Starker Fuß",positions:"Nebenpositionen",overview:"COPA-WERTE",playStyle:"SPIELROLLE",strengths:"STÄRKEN",risks:"SPIELRISIKEN",tendencies:"SPIELNEIGUNGEN",analysis:"KURZANALYSE",loading:"copa.life-Spielmodell wird geladen…",noModel:"Für diesen Spieler ist kein copa.life-Spielmodell verfügbar.",loadError:"Das Spielermodell konnte nicht geladen werden.",retry:"Erneut versuchen",positionFit:"Positionspassung",modelNote:"copa.life-Spielmodell · 0–100",impact:"Offensivwirkung",keeperImpact:"Paradenwirkung",build_up:"Spielaufbau",space_control:"Raumkontrolle",duels:"Duelle",engine:"Tempo und Ausdauer",pressure_decision:"Druck und Entscheidungen"},
  it:{open:"Apri profilo",close:"Chiudi profilo",age:"anni",club:"Club",country:"Livello nazionale",foot:"Piede preferito",positions:"Posizioni secondarie",overview:"PUNTEGGI COPA",playStyle:"RUOLO DI GIOCO",strengths:"PUNTI DI FORZA",risks:"RISCHI DI GIOCO",tendencies:"TENDENZE",analysis:"ANALISI",loading:"Caricamento del modello copa.life…",noModel:"Il modello copa.life non è disponibile per questo giocatore.",loadError:"Impossibile caricare il modello.",retry:"Riprova",positionFit:"Compatibilità ruolo",modelNote:"modello di gioco copa.life · 0–100",impact:"Impatto offensivo",keeperImpact:"Impatto parate",build_up:"Costruzione",space_control:"Controllo degli spazi",duels:"Duelli",engine:"Ritmo e resistenza",pressure_decision:"Pressione e decisioni"}
};

const insightCopy={
  tr:{strength:{impact:"Son bölgede yüksek etki",shot_stopping:"Kurtarış etkisi güçlü",build_up:"Temiz oyun kurulumu",space_control:"Alan okumada güçlü",duels:"İkili mücadelede etkili",engine:"Yüksek tempoyu sürdürüyor",pressure_decision:"Baskı altında güvenilir"},risk:{impact:"Son bölge etkisi sınırlı",build_up:"Kurulumda top kaybı riski",space_control:"Alan savunmasında destek ihtiyacı",duels:"Fiziksel eşleşmelerde risk",engine:"Yoğun tempoda düşüş riski",pressure_decision:"Baskı anında dalgalı tepki"},tendency:{contact_play:"Temaslı oyun eğilimi",direct_play:"Doğrudan oyun eğilimi",controlled_play:"Kontrollü oyun eğilimi"}},
  en:{strength:{impact:"Strong final-third impact",shot_stopping:"Strong saving impact",build_up:"Clean build-up play",space_control:"Strong space reading",duels:"Effective in duels",engine:"Sustains a high tempo",pressure_decision:"Reliable under pressure"},risk:{impact:"Limited final-third impact",build_up:"Turnover risk in build-up",space_control:"Needs support controlling space",duels:"Risk in physical matchups",engine:"May fade at high intensity",pressure_decision:"Variable response under pressure"},tendency:{contact_play:"Contact-heavy play tendency",direct_play:"Direct play tendency",controlled_play:"Controlled play tendency"}},
  es:{strength:{impact:"Alto impacto ofensivo",shot_stopping:"Gran impacto en paradas",build_up:"Construcción limpia",space_control:"Buena lectura de espacios",duels:"Eficaz en duelos",engine:"Mantiene un ritmo alto",pressure_decision:"Fiable bajo presión"},risk:{impact:"Impacto ofensivo limitado",build_up:"Riesgo de pérdida en salida",space_control:"Necesita apoyo en espacios",duels:"Riesgo en duelos físicos",engine:"Puede bajar con alta intensidad",pressure_decision:"Respuesta variable bajo presión"},tendency:{contact_play:"Tendencia al juego de contacto",direct_play:"Tendencia al juego directo",controlled_play:"Tendencia al juego controlado"}},
  de:{strength:{impact:"Hohe Offensivwirkung",shot_stopping:"Starke Paradenwirkung",build_up:"Sauberer Spielaufbau",space_control:"Gute Raumkontrolle",duels:"Wirksam in Duellen",engine:"Hält hohes Tempo",pressure_decision:"Verlässlich unter Druck"},risk:{impact:"Begrenzte Offensivwirkung",build_up:"Ballverlustrisiko im Aufbau",space_control:"Braucht Hilfe bei der Raumkontrolle",duels:"Risiko in körperlichen Duellen",engine:"Kann bei hoher Intensität abbauen",pressure_decision:"Schwankende Reaktion unter Druck"},tendency:{contact_play:"Kontaktbetonte Spielweise",direct_play:"Direkte Spielweise",controlled_play:"Kontrollierte Spielweise"}},
  it:{strength:{impact:"Forte impatto offensivo",shot_stopping:"Forte impatto nelle parate",build_up:"Costruzione pulita",space_control:"Buona lettura degli spazi",duels:"Efficace nei duelli",engine:"Sostiene un ritmo alto",pressure_decision:"Affidabile sotto pressione"},risk:{impact:"Impatto offensivo limitato",build_up:"Rischio palla persa in costruzione",space_control:"Richiede supporto negli spazi",duels:"Rischio nei duelli fisici",engine:"Può calare ad alta intensità",pressure_decision:"Risposta variabile sotto pressione"},tendency:{contact_play:"Tendenza al gioco di contatto",direct_play:"Tendenza al gioco diretto",controlled_play:"Tendenza al gioco controllato"}}
};

const archetypes={
  tr:{build_keeper:"Kurucu Kaleci",area_keeper:"Alan Kalecisi",duel_keeper:"Bire Bir Kalecisi",shot_stopper:"Kurtarış Kalecisi",pressing_forward:"Pres Forveti",link_forward:"Bağlantı Forveti",target_forward:"Mücadele Forveti",finisher:"Bitirici",creative_wide:"Yaratıcı Kanat",direct_wide:"Doğrudan Kanat",build_defender:"Kurucu Savunmacı",duel_defender:"Mücadele Savunmacısı",running_defender:"Tempolu Savunmacı",space_defender:"Alan Savunmacısı",ball_winner:"Top Kazanan",deep_builder:"Derin Kurucu",playmaker:"Oyun Kurucu",tempo_midfielder:"Tempolu Orta Saha",balanced_midfielder:"Dengeli Orta Saha"},
  en:{build_keeper:"Build-up Keeper",area_keeper:"Area Keeper",duel_keeper:"Duel Keeper",shot_stopper:"Shot Stopper",pressing_forward:"Pressing Forward",link_forward:"Link Forward",target_forward:"Duel Forward",finisher:"Finisher",creative_wide:"Creative Wide Player",direct_wide:"Direct Wide Player",build_defender:"Build-up Defender",duel_defender:"Duel Defender",running_defender:"High-tempo Defender",space_defender:"Space Defender",ball_winner:"Ball Winner",deep_builder:"Deep Builder",playmaker:"Playmaker",tempo_midfielder:"Tempo Midfielder",balanced_midfielder:"Balanced Midfielder"}
};

const NATIONAL_TEAM_LEVELS={
  ana:{label:{tr:"A Milli",en:"Senior",es:"Absoluta",de:"A-Nationalteam",it:"Nazionale maggiore"},code:"A"},
  "u 23":{label:{tr:"U-23",en:"U-23",es:"Sub-23",de:"U-23",it:"U-23"},code:"U23"},
  "u 21":{label:{tr:"U-21",en:"U-21",es:"Sub-21",de:"U-21",it:"U-21"},code:"U21"},
  "u 20":{label:{tr:"U-20",en:"U-20",es:"Sub-20",de:"U-20",it:"U-20"},code:"U20"},
  "u 19":{label:{tr:"U-19",en:"U-19",es:"Sub-19",de:"U-19",it:"U-19"},code:"U19"}
};

function t(){return copy[global.LANG]||copy.en;}
function esc(value){return String(value==null?"":value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[ch]);}
function number(value){if(value===null||value===undefined||value==="")return null;const result=Number(value);return Number.isFinite(result)?result:null;}
function playerKey(player){return player&&(player.profileKey||player.profile_key)||[global.selectedCountry||"",player&&player.name||"",player&&player.club||"",player&&player.age||"",player&&player.ov||""].join("|");}
function ratingColor(value){const n=Math.max(0,Math.min(100,number(value)||0));if(typeof global.ovCol==="function")return global.ovCol(n);return n>=85?"#15803d":n>=72?"#4ade80":n>=58?"#eab308":n>=45?"#f97316":"#ef4444";}
function positionLabel(pos){if(!pos)return"";const dict=typeof global.L==="function"&&global.L().abbr;return dict&&dict[pos]||pos;}
function splitPositions(value){return String(value||"").split(/[,;|]+/).map(v=>v.trim()).filter(Boolean);}
function uniqueValues(values){const seen=new Set();return values.filter(value=>{const key=String(value||"").toLocaleLowerCase("tr-TR");if(!key||seen.has(key))return false;seen.add(key);return true;});}
function lookupKey(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("en-US").replace(/[^a-z0-9]+/g," ").trim();}
function nationalTeamInfo(value){const raw=String(value||"").trim(),key=lookupKey(raw),entry=NATIONAL_TEAM_LEVELS[key]||null;return entry?{label:entry.label[global.LANG]||entry.label.en,code:entry.code,flag:""}:{label:raw,code:key.replace(/\s+/g,"").slice(0,3).toUpperCase()||"--",flag:""};}
function detailMonogram(value){const parts=String(value||"").trim().split(/\s+/).filter(Boolean);return(parts.length>1?parts[0][0]+parts[parts.length-1][0]:String(value||"").slice(0,2)).toUpperCase();}
function isKeeper(player,profile){const raw=[player&&player.natPos,player&&player.pos,profile&&profile.best_position,profile&&profile.secondary_position,profile&&profile.positions].filter(Boolean).join(" ").toUpperCase();return /(^|[\s,(])(?:GK|KL)(?:$|[\s,)])/.test(raw);}
function footLabel(value){const raw=String(value||"");if((global.LANG||"tr")==="tr")return raw;const two=/iki aya/i.test(raw),left=/sol/i.test(raw);if(global.LANG==="es")return two?"Ambidiestro":left?"Zurdo":"Diestro";if(global.LANG==="de")return two?"Beidfüßig":left?"Linksfuß":"Rechtsfuß";if(global.LANG==="it")return two?"Ambidestro":left?"Mancino":"Destro";return two?"Two footed":left?"Left footed":"Right footed";}
function clubLogoMap(){const code=global.selectedCountry||"TR",maps={TR:global.CLUB_LOGOS_SM,ENG:global.CLUB_LOGOS_EN_SM,ES:global.CLUB_LOGOS_ES_SM,IT:global.CLUB_LOGOS_IT_SM,DE:global.CLUB_LOGOS_DE_SM,JP:global.CLUB_LOGOS_JP_SM};return maps[code]||{};}
function clubLogoFor(club){if(global.COPA_PLATFORM==="android")return"";const map=clubLogoMap();if(!club)return"";if(map[club])return map[club];const key=lookupKey(club),match=Object.keys(map).find(name=>lookupKey(name)===key);return match?map[match]:"";}
function genericCrestFor(club){return global.COPA_PLATFORM==="android"&&global.CopaClubVisuals&&typeof global.CopaClubVisuals.crestFor==="function"?global.CopaClubVisuals.crestFor(club):null;}
function dimensionLabel(key,keeper){const labels=t();return key==="impact"&&keeper?labels.keeperImpact:labels[key]||key;}
function insightLabel(id,kind,keeper){const lang=insightCopy[global.LANG]||insightCopy.en,map=lang[kind]||{};return map[id]||map[id==="shot_stopping"?"shot_stopping":id]||id;}
function roleLabel(id){const map=archetypes[global.LANG]||archetypes.en;return map[id]||(archetypes.en[id]||id);}

function radarClusters(player,profile){const keeper=isKeeper(player,profile);return DIMENSION_KEYS.map(key=>{const value=number(profile&&profile["copa_"+key]);return value==null?null:{key,label:dimensionLabel(key,keeper),value:Math.round(Math.max(0,Math.min(100,value)))};}).filter(Boolean);}
function profileInsights(profile,keeper){const strengthIds=Array.isArray(profile&&profile.strengths)?profile.strengths:[],riskIds=Array.isArray(profile&&profile.risks)?profile.risks:[],tendencyIds=Array.isArray(profile&&profile.tendencies)?profile.tendencies:[];return {strengths:strengthIds.map(id=>({id,label:insightLabel(id,"strength",keeper)})),risks:riskIds.map(id=>({id,label:insightLabel(id,"risk",keeper)})),tendencies:tendencyIds.map(id=>({id,label:insightLabel(id,"tendency",keeper)}))};}
function analysisFor(radar){if(radar.length!==6)return"";const sorted=radar.slice().sort((a,b)=>b.value-a.value),strong=sorted[0],risk=sorted[sorted.length-1],lang=global.LANG||"en";if(lang==="tr")return strong.label+" öne çıkan alanı. "+(risk.value<=55?risk.label+" maç planında desteklenmeli.":"Profil belirgin bir zayıflık göstermiyor.");if(lang==="es")return strong.label+" es su área principal. "+(risk.value<=55?"Conviene apoyar "+risk.label.toLowerCase()+".":"El perfil no muestra una debilidad marcada.");if(lang==="de")return strong.label+" ist der stärkste Bereich. "+(risk.value<=55?risk.label+" sollte im Matchplan gestützt werden.":"Das Profil zeigt keine klare Schwäche.");if(lang==="it")return strong.label+" è l'area principale. "+(risk.value<=55?"Il piano gara dovrebbe sostenere "+risk.label.toLowerCase()+".":"Il profilo non mostra debolezze marcate.");return strong.label+" is the standout area. "+(risk.value<=55?risk.label+" should be supported by the match plan.":"The profile shows no pronounced weakness.");}
function normalize(player,profile,options){
  const opts=options||{},keeper=isKeeper(player,profile),pos=positionLabel(player.natPos||player.pos),bestParts=splitPositions(profile&&profile.best_position),secondaryParts=splitPositions(profile&&profile.secondary_position),known=bestParts.concat(secondaryParts,splitPositions(profile&&profile.positions)),primary=bestParts[0]||pos,positions=uniqueValues(known.length?known:(pos?[pos]:[])),radar=profile?radarClusters(player,profile):[],insights=profileInsights(profile,keeper),nationalTeam=nationalTeamInfo(profile&&profile.national_team),crest=genericCrestFor(player.club||"");
  return {key:playerKey(player),name:player.name||"",ov:number(player.ov),age:number(player.age),position:primary,club:player.club||"",clubLogo:clubLogoFor(player.club||""),genericCrest:crest,country:nationalTeam.label,countryCode:nationalTeam.code,countryFlag:nationalTeam.flag,foot:footLabel(profile&&profile.preferred_foot),best:primary,secondary:secondaryParts[0]||"",positions,secondaryPositions:positions.filter(value=>value!==primary),radar,radarReady:radar.length===6,strengths:insights.strengths,risks:insights.risks,tendencies:insights.tendencies,playStyle:profile?roleLabel(profile.archetype):"",analysis:profile?analysisFor(radar):"",positionFit:number(profile&&profile.position_fit),goalkeeperProfile:keeper,modelVersion:profile&&profile.model_version||MODEL_VERSION,loading:!!opts.loading,loadError:opts.loadError||null,hasModel:!!profile&&radar.length===6,sourceType:profile&&profile.source_type||"none"};
}
function debugProfile(player,data){const host=global.location&&global.location.hostname||"",enabled=host==="localhost"||host==="127.0.0.1"||/(?:^|[?&])debug=1(?:&|$)/.test(global.location&&global.location.search||"");if(enabled&&global.console&&typeof global.console.debug==="function")global.console.debug("[PlayerProfiles]",{playerId:player&&player.profileKey||null,sourceType:data.sourceType,modelVersion:data.modelVersion,goalkeeperProfile:data.goalkeeperProfile,copaDimensions:data.radar.map(item=>item.key+":"+item.value),positionFit:data.positionFit});}
function profileCacheKey(player){return[playerKey(player),global.LANG||"tr",player.ov||"",player.natPos||"",player.pos||"",player.club||"",player.age||"",global.COPA_PLATFORM||"web"].join("|");}
function profileLoader(player){return typeof global.playerProfileForPlayerAsync==="function"?global.playerProfileForPlayerAsync(player,global.selectedCountry||"TR"):player.profileKey&&typeof global.playerProfileByKeyAsync==="function"?global.playerProfileByKeyAsync(player.profileKey):typeof global.playerProfileForAsync==="function"?global.playerProfileForAsync(global.selectedCountry||"TR",player.name,player.club,player.age):Promise.resolve(null);}
function profileFor(player,options){const opts=options||{},key=profileCacheKey(player);if(!opts.force&&normalizedCache.has(key))return Promise.resolve(normalizedCache.get(key));const start=opts.force&&typeof global.retryPlayerProfiles==="function"?global.retryPlayerProfiles():Promise.resolve();return start.then(()=>profileLoader(player)).then(profile=>{const value=normalize(player,profile);normalizedCache.set(key,value);debugProfile(player,value);return value;}).catch(error=>{if(global.CopaAnalytics)global.CopaAnalytics.track("profile_open_error",{detail:opts.force?"retry_failed":"load_failed"});const value=normalize(player,null,{loadError:error||new Error("PLAYER_PROFILE_LOAD_FAILED")});debugProfile(player,value);return value;});}

function ensureDom(){
  if(root)return;root=document.createElement("div");root.className="player-profile-layer hidden";root.setAttribute("aria-hidden","true");root.innerHTML='<div class="player-profile-backdrop" data-profile-close></div><section class="player-profile-card" role="dialog"><button class="player-profile-close" type="button" data-profile-close></button><div class="player-profile-content"></div></section>';document.body.appendChild(root);panel=root.querySelector(".player-profile-card");
  root.addEventListener("click",event=>{if(event.target.closest("[data-profile-retry]")){retryCurrent();return;}if(event.target.closest("[data-profile-close]"))close();});
  root.addEventListener("error",event=>{const image=event.target&&event.target.closest&&event.target.closest("[data-profile-club-logo],[data-profile-country-flag]");if(!image)return;image.hidden=true;if(image.parentElement)image.parentElement.classList.add("is-fallback");},true);
  root.addEventListener("keydown",event=>{if(!current||finePointer()||event.key!=="Tab")return;const focusable=Array.from(panel.querySelectorAll('button,a,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')).filter(element=>!element.disabled&&element.offsetParent!==null);if(!focusable.length){event.preventDefault();panel.focus();return;}const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
  panel.addEventListener("mouseenter",cancelClose);panel.addEventListener("mouseleave",scheduleClose);
}
function clubVisualHtml(data){if(data.genericCrest)return '<span class="player-profile-detail-media is-generic-crest" style="--crest-a:'+esc(data.genericCrest.colors[0])+';--crest-b:'+esc(data.genericCrest.colors[1])+'"><i>'+esc(data.genericCrest.code)+'</i></span>';const fallback='<i class="player-profile-detail-fallback" aria-hidden="true">'+esc(detailMonogram(data.club))+'</i>';return '<span class="player-profile-detail-media'+(data.clubLogo?'':' is-fallback')+'">'+(data.clubLogo?'<img src="'+esc(data.clubLogo)+'" alt="" loading="lazy" decoding="async" data-profile-club-logo>':'')+fallback+'</span>';}
function countryVisualHtml(data){const fallback='<i class="player-profile-detail-fallback is-flag is-country-code" aria-hidden="true">'+esc(data.countryCode||"--")+'</i>';return '<span class="player-profile-detail-media is-country'+(data.countryFlag?'':' is-fallback')+'">'+(data.countryFlag?'<img src="'+esc(data.countryFlag)+'" alt="" loading="lazy" decoding="async" data-profile-country-flag>':'')+fallback+'</span>';}
function detailHtml(label,value,visual,kind){return '<div class="player-profile-detail is-'+kind+'"><b>'+esc(label)+'</b><span class="player-profile-detail-value">'+(visual||'')+'<em>'+esc(value)+'</em></span></div>';}
function identityHtml(data){const c=t(),meta=[];if(data.age!=null)meta.push(esc(data.age+" "+c.age));if(data.position)meta.push('<span class="player-profile-primary-pos">'+esc(data.position)+'</span>');const details=[];if(data.club)details.push(detailHtml(c.club,data.club,clubVisualHtml(data),"club"));if(data.country)details.push(detailHtml(c.country,data.country,countryVisualHtml(data),"country"));if(data.foot)details.push(detailHtml(c.foot,data.foot,"","foot"));return '<header class="player-profile-head"><div class="player-profile-monogram" aria-hidden="true">'+esc((typeof global._playerMonogram==="function"?global._playerMonogram(data.name):data.name.slice(0,2)).toUpperCase())+'</div><div class="player-profile-id"><div class="player-profile-name-row"><h2 id="playerProfileTitle">'+esc(data.name)+'</h2>'+(data.ov!=null?'<strong class="player-profile-ov" style="--profile-tone:'+ratingColor(data.ov)+'">'+esc(data.ov)+'</strong>':"")+'</div>'+(meta.length?'<p>'+meta.join('<i aria-hidden="true">·</i>')+'</p>':"")+'</div></header>'+(details.length?'<div class="player-profile-details">'+details.join("")+'</div>':"");}
function positionsHtml(data){if(!data.secondaryPositions.length)return"";return '<div class="player-profile-positions"><h3>'+esc(t().positions)+'</h3><div class="player-profile-pos-list">'+data.secondaryPositions.map(pos=>'<span class="player-profile-pos is-secondary">'+esc(pos)+'</span>').join("")+'</div></div>';}
function radarPoint(index,ratio,radius){const angle=(-Math.PI/2)+(Math.PI*2/6)*index;return[120+Math.cos(angle)*radius*ratio,120+Math.sin(angle)*radius*ratio];}
function radarPolygon(ratio,radius){return [0,1,2,3,4,5].map(index=>{const point=radarPoint(index,ratio,radius);return point[0].toFixed(1)+","+point[1].toFixed(1);}).join(" ");}
function radarHtml(data){if(!data.radarReady)return"";const c=t(),radius=72,grids=[.25,.5,.75,1].map(level=>'<polygon class="player-profile-radar-grid" points="'+radarPolygon(level,radius)+'"></polygon>').join(""),axes=data.radar.map((_,index)=>{const point=radarPoint(index,1,radius);return '<line class="player-profile-radar-axis" x1="120" y1="120" x2="'+point[0].toFixed(1)+'" y2="'+point[1].toFixed(1)+'"></line>';}).join(""),area=data.radar.map((cluster,index)=>{const point=radarPoint(index,cluster.value/100,radius);return point[0].toFixed(1)+","+point[1].toFixed(1);}).join(" "),dots=data.radar.map((cluster,index)=>{const point=radarPoint(index,cluster.value/100,radius);return '<circle class="player-profile-radar-dot" cx="'+point[0].toFixed(1)+'" cy="'+point[1].toFixed(1)+'" r="2"></circle>';}).join(""),labels=data.radar.map((cluster,index)=>{const point=radarPoint(index,1,101),anchor=point[0]<90?"end":point[0]>150?"start":"middle",dy=index===0?"0":index===3?"8":"3";return '<text x="'+point[0].toFixed(1)+'" y="'+point[1].toFixed(1)+'" text-anchor="'+anchor+'" dy="'+dy+'">'+esc(cluster.label)+'</text>';}).join(""),scores=data.radar.map(cluster=>'<span><i>'+esc(cluster.label)+'</i><b style="color:'+ratingColor(cluster.value)+'">'+esc(cluster.value)+'</b></span>').join(""),fit=data.positionFit!=null?'<div class="player-profile-fit"><span>'+esc(c.positionFit)+'</span><strong>'+esc(data.positionFit)+'%</strong></div>':"";return '<div class="player-profile-radar"><h3>'+esc(c.overview)+'</h3><svg viewBox="0 0 240 240" role="img" aria-label="'+esc(c.overview)+'">'+grids+axes+'<polygon class="player-profile-radar-area" points="'+area+'"></polygon>'+dots+labels+'</svg><div class="player-profile-radar-scores">'+scores+'</div>'+fit+'<p class="player-profile-model-note">'+esc(c.modelNote)+'</p></div>';}
function insightBlock(title,items,kind){if(!items.length)return"";return '<div class="player-profile-insights is-'+kind+'"><h3>'+esc(title)+'</h3><ul>'+items.map(item=>'<li><i aria-hidden="true"></i>'+esc(item.label)+'</li>').join("")+'</ul></div>';}
function overviewHtml(data){if(!data.hasModel)return"";const c=t(),style=data.playStyle?'<div class="player-profile-style"><h3>'+esc(c.playStyle)+'</h3><strong>'+esc(data.playStyle)+'</strong></div>':"",insights='<div class="player-profile-insight-grid">'+insightBlock(c.strengths,data.strengths,"positive")+insightBlock(c.risks,data.risks,"negative")+'</div>',tendencies=insightBlock(c.tendencies,data.tendencies,"tendency"),analysis=data.analysis?'<div class="player-profile-analysis"><h3>'+esc(c.analysis)+'</h3><p>'+esc(data.analysis)+'</p></div>':"";return '<section class="player-profile-overview">'+radarHtml(data)+'<div class="player-profile-narrative">'+style+insights+tendencies+analysis+positionsHtml(data)+'</div></section>';}
function stateHtml(data){const c=t();if(data.loading)return '<section class="player-profile-section player-profile-state is-loading" role="status">'+esc(c.loading)+'</section>';if(data.loadError)return '<section class="player-profile-section player-profile-state is-error" role="alert"><span>'+esc(c.loadError)+'</span><button type="button" data-profile-retry>'+esc(c.retry)+'</button></section>';if(!data.hasModel)return '<section class="player-profile-section player-profile-state is-empty" role="status">'+esc(c.noModel)+'</section>';return"";}
function profileHtml(data){return identityHtml(data)+overviewHtml(data)+stateHtml(data);}
function render(data){if(!panel)return;panel.querySelector(".player-profile-close").setAttribute("aria-label",t().close);panel.querySelector(".player-profile-close").innerHTML="&times;";panel.setAttribute("aria-labelledby","playerProfileTitle");panel.querySelector(".player-profile-content").innerHTML=profileHtml(data);}
function place(){if(!current||!panel||!finePointer())return;const anchor=current.anchor;if(!anchor||!anchor.isConnected){close();return;}const a=anchor.getBoundingClientRect(),p=panel.getBoundingClientRect(),gap=10,edge=10;let left=a.right+gap,top=a.top+(a.height-p.height)/2;if(left+p.width>innerWidth-edge)left=a.left-p.width-gap;if(left<edge){left=Math.max(edge,Math.min(a.left+(a.width-p.width)/2,innerWidth-p.width-edge));top=a.bottom+gap;if(top+p.height>innerHeight-edge)top=a.top-p.height-gap;}panel.style.left=Math.round(Math.max(edge,Math.min(left,innerWidth-p.width-edge)))+"px";panel.style.top=Math.round(Math.max(edge,Math.min(top,innerHeight-p.height-edge)))+"px";}
function finePointer(){return !!(global.matchMedia&&global.matchMedia("(hover: hover) and (pointer: fine)").matches);}
function open(player,anchor,reason){if(!player||player.hidden||dragging||performance.now()<dragSuppressUntil)return;clearTimeout(openTimer);clearTimeout(closeTimer);ensureDom();const wasOpen=!!current,token=++requestId,isSheet=!finePointer();previousFocus=document.activeElement;current={player,anchor,reason:reason||"api"};root.classList.remove("hidden");root.classList.toggle("is-sheet",isSheet);document.body.classList.toggle("player-profile-open",isSheet);root.setAttribute("aria-hidden","false");panel.setAttribute("aria-modal",isSheet?"true":"false");render(normalize(player,null,{loading:true}));requestAnimationFrame(place);if(isSheet&&!wasOpen&&!historyPushed){try{history.pushState(Object.assign({},history.state,{copaPlayerProfile:true}),"");historyPushed=true;}catch(_){}}profileFor(player).then(data=>{if(!current||token!==requestId)return;render(data);requestAnimationFrame(place);});if(reason==="keyboard"||isSheet)requestAnimationFrame(()=>{const button=panel&&panel.querySelector(".player-profile-close");if(button)button.focus({preventScroll:true});});}
function close(fromHistory){clearTimeout(openTimer);clearTimeout(closeTimer);requestId++;if(!root||!current)return;root.classList.add("hidden");root.setAttribute("aria-hidden","true");document.body.classList.remove("player-profile-open");panel.style.left="";panel.style.top="";current=null;if(historyPushed&&!fromHistory){historyPushed=false;try{history.back();}catch(_){}}else if(fromHistory)historyPushed=false;if(previousFocus&&previousFocus.isConnected){try{previousFocus.focus({preventScroll:true});}catch(_){}}previousFocus=null;}
function cancelClose(){clearTimeout(closeTimer);}
function scheduleClose(){if(!finePointer())return;clearTimeout(closeTimer);closeTimer=setTimeout(()=>close(),HOVER_CLOSE_MS);}
function scheduleOpen(element){if(!finePointer()||dragging||performance.now()<dragSuppressUntil)return;clearTimeout(closeTimer);clearTimeout(openTimer);openTimer=setTimeout(()=>{const meta=bound.get(element);if(meta)open(meta.player,element,"hover");},HOVER_OPEN_MS);}
function bind(element,player,options){if(!element||!player||player.hidden)return element;const old=bound.get(element),opts=Object.assign({delayCoarseAction:false},options||{}),base=(old&&element.getAttribute("aria-label")===old.aria)?old.base:(element.getAttribute("aria-label")||player.name||""),aria=(base?base+". ":"")+t().open,meta=old||{};Object.assign(meta,{player,options:opts,base,aria});bound.set(element,meta);element.dataset.playerProfile="true";element.setAttribute("aria-label",aria);if(element.tagName!=="BUTTON"&&element.tagName!=="A"){if(!element.hasAttribute("role"))element.setAttribute("role","button");if(!element.hasAttribute("tabindex"))element.tabIndex=0;}if(!old){element.addEventListener("mouseenter",()=>scheduleOpen(element));element.addEventListener("mouseleave",scheduleClose);element.addEventListener("keydown",event=>{if(event.key!=="Enter"&&event.key!==" ")return;event.preventDefault();event.stopImmediatePropagation();const value=bound.get(element);if(value)open(value.player,element,"keyboard");});}return element;}
function bindSelector(rootNode,selector,players,options){Array.from(rootNode.querySelectorAll(selector)).forEach((element,index)=>{if(players[index])bind(element,players[index],options);});}
function setDragging(value){dragging=!!value;if(dragging){dragSuppressUntil=Infinity;close();}else dragSuppressUntil=performance.now()+380;}
function interceptCoarseClick(event){if(finePointer()||event.detail===0)return;const element=event.target.closest&&event.target.closest("[data-player-profile='true']");if(!element)return;if(replaying.has(element)){replaying.delete(element);return;}if(dragging||performance.now()<dragSuppressUntil){event.preventDefault();event.stopImmediatePropagation();return;}const meta=bound.get(element);if(!meta)return;const now=performance.now(),key=playerKey(meta.player);if(lastTap&&lastTap.key===key&&now-lastTap.at<=DOUBLE_TAP_MS){event.preventDefault();event.stopImmediatePropagation();if(lastTap.timer)clearTimeout(lastTap.timer);lastTap=null;open(meta.player,element,"double-tap");return;}lastTap={key,at:now,element,timer:0};if(meta.options.delayCoarseAction){event.preventDefault();event.stopImmediatePropagation();lastTap.timer=setTimeout(()=>{if(!lastTap||lastTap.element!==element)return;lastTap=null;if(!element.isConnected)return;replaying.add(element);element.click();queueMicrotask(()=>replaying.delete(element));},DOUBLE_TAP_MS+10);}}
document.addEventListener("click",interceptCoarseClick,true);document.addEventListener("dragstart",event=>{if(event.target.closest&&event.target.closest("[data-player-profile='true']"))setDragging(true);},true);document.addEventListener("dragend",()=>{if(dragging)setDragging(false);},true);document.addEventListener("drop",()=>{if(dragging)setDragging(false);},true);document.addEventListener("keydown",event=>{if(event.key==="Escape"&&current){event.preventDefault();close();}});global.addEventListener("resize",()=>{if(current){if(finePointer())place();else close();}},{passive:true});global.addEventListener("orientationchange",()=>{if(current)close();},{passive:true});global.addEventListener("popstate",()=>{if(current&&historyPushed)close(true);});
function refresh(){document.querySelectorAll("[data-player-profile='true']").forEach(element=>{const meta=bound.get(element);if(meta)bind(element,meta.player,meta.options);});if(!current)return;const token=++requestId,player=current.player;render(normalize(player,null,{loading:true}));profileFor(player).then(data=>{if(!current||token!==requestId)return;render(data);requestAnimationFrame(place);});}
function retryCurrent(){if(!current)return;const token=++requestId,player=current.player;normalizedCache.delete(profileCacheKey(player));render(normalize(player,null,{loading:true}));requestAnimationFrame(place);profileFor(player,{force:true}).then(data=>{if(!current||token!==requestId)return;render(data);requestAnimationFrame(place);});}
global.PlayerProfiles={bind,bindSelector,open,close,refresh,retry:retryCurrent,setDragging,isOpen:()=>!!current,_normalizedCache:normalizedCache,_normalizeForTest:normalize,_renderForTest:profileHtml};
})(window);
