/* Risk/odul draftlari ve tur ici zorluk carpanlari. */
function maybeDraftEvent(){if(round<2||round>5||eventSeen[round]||runEnded)return;eventSeen[round]=1;if(rand()>0.75)return;setTimeout(showDraftEvent,260);}
function showDraftEvent(){
 if($("hub").classList.contains("hidden"))return;const tr=LANG==="tr";
 const _bolt=`<svg viewBox='0 0 22 32' width='22' height='28' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M14 2L5 17H12L8 30L19 14H12L14 2Z' fill='currentColor' opacity='.18'/><path d='M14 2L5 17H12L8 30L19 14H12L14 2Z'/></svg>`;
 const _case=`<svg viewBox='0 0 32 26' width='28' height='24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='2' y='8' width='28' height='16' rx='2.5'/><path d='M11 8V6a3 3 0 0 1 3-3h4a3 3 0 0 1 3 3v2'/><line x1='2' y1='16' x2='30' y2='16'/></svg>`;
 const _dice=`<svg viewBox='0 0 28 28' width='26' height='26' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='2' y='2' width='24' height='24' rx='4'/><circle cx='9' cy='9' r='2.2' fill='currentColor'/><circle cx='19' cy='9' r='2.2' fill='currentColor'/><circle cx='9' cy='19' r='2.2' fill='currentColor'/><circle cx='19' cy='19' r='2.2' fill='currentColor'/><circle cx='14' cy='14' r='2.2' fill='currentColor'/></svg>`;
 const _band=`<svg viewBox='0 0 36 28' width='30' height='24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='4' y='8' width='28' height='12' rx='5' transform='rotate(-15 18 14)'/><line x1='18' y1='10' x2='18' y2='18'/><line x1='14' y1='14' x2='22' y2='14'/></svg>`;
 const _hand=`<svg viewBox='0 0 26 32' width='22' height='28' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M7 18V8a2.5 2.5 0 0 1 5 0v5'/><path d='M12 8V6a2.5 2.5 0 0 1 5 0v8'/><path d='M17 9V7a2.5 2.5 0 0 1 5 0v6'/><path d='M7 18c0 6 3 10 9 10s9-4 9-10v-5'/></svg>`;
 const opts=[
  {i:_bolt,c:"#f59e0b",n:tr?"Yüksek Tempo":"High Tempo",d:tr?"Bu tur +6 güç, -€8M, sonraki tur -2 güç":"This round +6 power, -€8M, next round -2 power",go:()=>{riskPowerMod+=6;spend(8,"spent");talkMod.all-=2;pushFeed("⚡ +6 / -€8 / -2","pres");}},
  {i:_case,c:"#16a34a",n:tr?"Kumarbaz Sponsor":"Gambler Sponsor",d:tr?"+€14M, bu tur -2 güç, %25 ihtimal -€10M, finalde -4 güç":"+€14M, this round -2 power, 25% chance -€10M, final -4 power",go:()=>{earn(14,"earned");riskPowerMod-=2;finalPenalty=Math.min(FINAL_DEBT_CAP,finalPenalty+4);let msg="\u{1f4bc} +€14 / -2 / final -"+finalPenalty;if(rand()<0.25){spend(10,"spent");msg+=" / -€10";}pushFeed(msg,"buy");}},
  {i:_dice,c:"#7c3aed",n:tr?"Finale Yaz":"Write It To Final",d:tr?"Şimdi +€8M ve +3 güç, finalde -8 güç":"Now +€8M and +3 power, final -8 power",go:()=>{earn(8,"earned");riskPowerMod+=3;finalPenalty=Math.min(FINAL_DEBT_CAP,finalPenalty+8);pushFeed("\u{1f3b2} "+(tr?"finalde eksi güç":"final power loss")+" -"+finalPenalty,"pres");}},
  {i:_band,c:"#dc2626",n:tr?"Gözü Kara":"Play Through Pain",d:tr?"Bu tur +5 güç, maç sonu %35 sakatlık riski":"This round +5 power, 35% post-match injury risk",go:()=>{riskPowerMod+=5;if(rand()<0.35){const p=applyRandomInjury(1);if(p)pushFeed("\u{1fa79} <b>"+shortName(p)+"</b> "+(tr?"zorlamadan sakatlandı":"was injured by the gamble"),"lose");}pushFeed("\u{1fa79} +5","pres");}}
 ];
 let h="<div><div class=\"kithdr\">"+(tr?"Risk/Ödül Draftı":"Risk/Reward Draft")+"</div><div class=\"kitsub\">"+(tr?"Güçlü ödül, gerçek bedel. Gerek yoksa pas geç.":"Strong reward, real cost. Skip if you do not need it.")+"</div><div class=\"stylelist\">";
 opts.forEach((o,i)=>{h+="<div class=\"stylebtn\" onclick=\"pickDraftEvent("+i+")\"><div class=\"ssi\" style=\"color:"+(o.c||"currentColor")+"\">"+o.i+"</div><div class=\"ssm\"><div class=\"sst\">"+o.n+"</div><div class=\"ssd\">"+o.d+"</div></div></div>";});
 h+="<div class=\"stylebtn\" onclick=\"pickDraftEvent(-1)\"><div class=\"ssi\">"+_hand+"</div><div class=\"ssm\"><div class=\"sst\">"+(tr?"Pas geç":"Skip")+"</div><div class=\"ssd\">"+(tr?"Risk alma, mevcut planla devam et.":"Take no risk and continue.")+"</div></div></div></div></div>";
 window._draftEvents=opts;showModal(h);
}
function pickDraftEvent(i){if(i<0){closeModal();return;}const o=window._draftEvents&&window._draftEvents[i];if(!o)return;closeModal();o.go();sfxStamp();setBudget();renderHub();}
