class_name AttackingSequence
extends RefCounted

const BUILD_UP_CENTER: String = "BUILD_UP_CENTER"
const ATTACK_LEFT: String = "ATTACK_LEFT"
const ATTACK_RIGHT: String = "ATTACK_RIGHT"
const DIRECT_LONG_BALL: String = "DIRECT_LONG_BALL"
const COUNTER_ATTACK: String = "COUNTER_ATTACK"
const RECYCLE_POSSESSION: String = "RECYCLE_POSSESSION"
const CROSS_SEQUENCE: String = "CROSS_SEQUENCE"
const CUTBACK_SEQUENCE: String = "CUTBACK_SEQUENCE"
const FINAL_THIRD_COMBINATION: String = "FINAL_THIRD_COMBINATION"
const SHOT_SEQUENCE: String = "SHOT_SEQUENCE"
const LOOSE_BALL_CONTEST: String = "LOOSE_BALL_CONTEST"

const PREPARE: String = "PREPARE"
const PROGRESS: String = "PROGRESS"
const FINAL_ACTION: String = "FINAL_ACTION"
const RECYCLE: String = "RECYCLE"
const BROKEN: String = "BROKEN"

static func is_valid(sequence: String) -> bool:
	return sequence in [
		BUILD_UP_CENTER,
		ATTACK_LEFT,
		ATTACK_RIGHT,
		DIRECT_LONG_BALL,
		COUNTER_ATTACK,
		RECYCLE_POSSESSION,
		CROSS_SEQUENCE,
		CUTBACK_SEQUENCE,
		FINAL_THIRD_COMBINATION,
		SHOT_SEQUENCE,
		LOOSE_BALL_CONTEST
	]
