class_name PossessionSequence
extends RefCounted

const BUILD_FROM_BACK_SHORT: String = "BUILD_FROM_BACK_SHORT"
const CENTER_TRIANGLE_BUILDUP: String = "CENTER_TRIANGLE_BUILDUP"
const WIDE_OVERLOAD_LEFT: String = "WIDE_OVERLOAD_LEFT"
const WIDE_OVERLOAD_RIGHT: String = "WIDE_OVERLOAD_RIGHT"
const DIRECT_LONG_BALL: String = "DIRECT_LONG_BALL"
const PRESSURED_RECYCLE: String = "PRESSURED_RECYCLE"
const SWITCH_PLAY_SEQUENCE: String = "SWITCH_PLAY_SEQUENCE"
const CUTBACK_ATTACK: String = "CUTBACK_ATTACK"
const COUNTER_ATTACK: String = "COUNTER_ATTACK"
const SET_PIECE_CORNER: String = "SET_PIECE_CORNER"
const SET_PIECE_RESTART: String = "SET_PIECE_RESTART"
const OFFSIDE_TRAP_OR_LINE_BREAK: String = "OFFSIDE_TRAP_OR_LINE_BREAK"
const FINAL_THIRD_COMBINATION: String = "FINAL_THIRD_COMBINATION"

const PREPARE: String = "PREPARE"
const PROGRESS: String = "PROGRESS"
const MOVE_OFF_BALL: String = "MOVE_OFF_BALL"
const RELEASE_PASS: String = "RELEASE_PASS"
const BALL_TRAVEL: String = "BALL_TRAVEL"
const RECEIVE: String = "RECEIVE"
const REACTION: String = "REACTION"
const FINAL_ACTION: String = "FINAL_ACTION"
const RESTART_SETUP: String = "RESTART_SETUP"
const BROKEN: String = "BROKEN"

const OPEN_PLAY_CONTINUOUS: String = "OPEN_PLAY_CONTINUOUS"
const RESTART_PLACED: String = "RESTART_PLACED"
const OUT_OF_PLAY_RESET: String = "OUT_OF_PLAY_RESET"

static func is_restart_continuity(value: String) -> bool:
	return value in [RESTART_PLACED, OUT_OF_PLAY_RESET]
