class_name SequenceRole
extends RefCounted

const NONE: String = "NONE"
const ACTIVE_BALL_CARRIER: String = "ACTIVE_BALL_CARRIER"
const PRIMARY_SUPPORT: String = "PRIMARY_SUPPORT"
const SECONDARY_SUPPORT: String = "SECONDARY_SUPPORT"
const WIDTH_HOLDER: String = "WIDTH_HOLDER"
const DEPTH_RUNNER: String = "DEPTH_RUNNER"
const FAR_SIDE_RUNNER: String = "FAR_SIDE_RUNNER"
const CUTBACK_OPTION: String = "CUTBACK_OPTION"
const BALANCE_HOLDER: String = "BALANCE_HOLDER"
const REST_DEFENSE: String = "REST_DEFENSE"
const PRIMARY_PRESSER: String = "PRIMARY_PRESSER"
const SECONDARY_COVER: String = "SECONDARY_COVER"
const COVER_SHADOW: String = "COVER_SHADOW"
const PASS_LANE_BLOCKER: String = "PASS_LANE_BLOCKER"
const BALL_SIDE_FULLBACK_PRESS: String = "BALL_SIDE_FULLBACK_PRESS"
const BALL_SIDE_MIDFIELD_COVER: String = "BALL_SIDE_MIDFIELD_COVER"
const WEAK_SIDE_COMPACTNESS: String = "WEAK_SIDE_COMPACTNESS"
const WEAK_SIDE_COMPACT: String = "WEAK_SIDE_COMPACT"
const LINE_HOLDER: String = "LINE_HOLDER"
const DEFENSIVE_LINE_HOLDER: String = "DEFENSIVE_LINE_HOLDER"
const BOX_PROTECTOR: String = "BOX_PROTECTOR"
const RUNNER_MARKER: String = "RUNNER_MARKER"
const MIDFIELD_SCREEN: String = "MIDFIELD_SCREEN"
const GOALKEEPER_COVER: String = "GOALKEEPER_COVER"
const GOALKEEPER: String = "GOALKEEPER"

static func is_active(role: String) -> bool:
	return role in [
		ACTIVE_BALL_CARRIER,
		PRIMARY_SUPPORT,
		SECONDARY_SUPPORT,
		DEPTH_RUNNER,
		FAR_SIDE_RUNNER,
		CUTBACK_OPTION,
		PRIMARY_PRESSER,
		SECONDARY_COVER,
		COVER_SHADOW,
		PASS_LANE_BLOCKER,
		BALL_SIDE_FULLBACK_PRESS,
		RUNNER_MARKER
	]
