/* Ses efektleri: Kenney UI audio + Web Audio fallback, zar, alkis, duduk, kalabalik, mute. */
let AC=null,crowdNodes=null;
window.CopaSfxMuted=()=>muted;
const UI_SFX_LAST=Object.create(null);
const UI_SFX={
 click:"assets/audio/ui/click1.ogg",stamp:"assets/audio/ui/click3.ogg",
 select:"assets/audio/ui/mouseclick1.ogg",release:"assets/audio/ui/mouserelease1.ogg",
 hover:"assets/audio/ui/rollover2.ogg",switch:"assets/audio/ui/switch10.ogg",
 buy:"assets/audio/ui/switch23.ogg",reward:"assets/audio/ui/switch33.ogg",
 championship:"assets/audio/ui/championship.ogg",eliminated:"assets/audio/ui/eliminated.ogg?v=20260714-elendin1",
 kickedout:"assets/audio/ui/kickedout.ogg",ghost:"assets/audio/ui/ghost.ogg?v=20260714-ghostsfx1",
 flag_TR:"assets/audio/ui/turkiye.ogg",flag_IT:"assets/audio/ui/switch33.ogg",
 flag_ENG:"assets/audio/ui/england.ogg",flag_ES:"assets/audio/ui/spain.ogg",
 flag_DE:"assets/audio/ui/germany.ogg",
 talk_gaz:"assets/audio/ui/atesle.ogg",talk_mantik:"assets/audio/ui/planihatirlat.ogg",
 talk_sert:"assets/audio/ui/disiplin.ogg",
 mode_life_select:"assets/audio/ui/copa-life-selected.ogg",
 mode_arena_select:"assets/audio/ui/copa-arena-selected.ogg"
};
function playUiSample(k,vol,cooldown){if(typeof muted!=="undefined"&&muted)return false;const src=UI_SFX[k];if(!src)return false;const now=performance.now(),wait=cooldown==null?65:cooldown,last=UI_SFX_LAST[k]||0;if(last&&now-last<wait)return false;UI_SFX_LAST[k]=now;try{const a=new Audio(src);a.preload="none";a.volume=vol==null?.22:vol;a.onended=()=>{a.removeAttribute("src");a.load();};const p=a.play();if(p&&p.catch)p.catch(()=>{});return true;}catch(e){return false;}}
function ac(){if(!AC){try{AC=new (window.AudioContext||window.webkitAudioContext)();}catch(e){}}return AC;}
function noiseBuf(c,dur){const n=Math.floor(c.sampleRate*dur),b=c.createBuffer(1,n,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=Math.random()*2-1;return b;}
function click(c,t,f,v,du){const o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.value=f;g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(v,t+0.004);g.gain.exponentialRampToValueAtTime(0.0001,t+du);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+du+0.01);}
function sfxRoll(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;let tt=0;for(let i=0;i<14;i++){click(c,t+tt,ri(160,360),0.03,0.03);tt+=0.03+i*0.006;}const src=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();src.buffer=noiseBuf(c,0.5);f.type="bandpass";f.frequency.value=900;g.gain.setValueAtTime(0.025,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.5);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);}
function sfxTick(){if(playUiSample("hover",.11))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;for(let i=0;i<3;i++)click(c,t+i*0.12,1200-i*200,0.025,0.04);}
function sfxModeChoice(mode){
 const choice=mode==="arena"?"arena":"life";
 return playUiSample("mode_"+choice+"_select",.34,0);
}
function sfxSeat(){if(playUiSample("select",.18))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.setValueAtTime(220,t);o.frequency.exponentialRampToValueAtTime(90,t+0.07);g.gain.setValueAtTime(0.06,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.1);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.11);click(c,t+0.02,520,0.025,0.02);}
function sfxStamp(){if(playUiSample("stamp",.17))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.setValueAtTime(170,t);o.frequency.exponentialRampToValueAtTime(55,t+0.12);g.gain.setValueAtTime(0.065,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.18);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.2);}
function sfxWhistle(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.setValueAtTime(1750,t);g.gain.setValueAtTime(0.001,t);g.gain.linearRampToValueAtTime(0.025,t+0.03);g.gain.setValueAtTime(0.025,t+0.16);g.gain.exponentialRampToValueAtTime(0.0001,t+0.28);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.3);}
function sfxKick(power){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const src=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();src.buffer=noiseBuf(c,0.06);f.type="bandpass";f.frequency.value=power>5?260:380;g.gain.setValueAtTime(power>5?0.04:0.018,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.06);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);}
function crowdStart(){if(muted||!ac())return;const c=AC;const src=c.createBufferSource();src.buffer=noiseBuf(c,2);src.loop=true;const f=c.createBiquadFilter();f.type="lowpass";f.frequency.value=520;const g=c.createGain();g.gain.value=0.014;src.connect(f);f.connect(g);g.connect(c.destination);src.start();crowdNodes={src,g};}
function crowdStop(){if(crowdNodes){try{crowdNodes.src.stop();}catch(e){}crowdNodes=null;}}
function crowdSwell(){if(!crowdNodes)return;const c=AC,t=c.currentTime,g=crowdNodes.g.gain;g.cancelScheduledValues(t);g.setValueAtTime(0.014,t);g.linearRampToValueAtTime(0.06,t+0.1);g.exponentialRampToValueAtTime(0.014,t+1.2);}
function paintMuteButton(){const _on='<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" width="14" height="14"><polygon points="2,7 6,7 11,3 11,17 6,13 2,13" fill="currentColor" stroke-linejoin="round"/><path d="M13.5 7.5Q15.5 10 13.5 12.5"/><path d="M16 5.5Q19 10 16 14.5"/></svg>';const _off='<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" width="14" height="14"><polygon points="2,7 6,7 11,3 11,17 6,13 2,13" fill="currentColor" stroke-linejoin="round"/><line x1="14" y1="7" x2="19" y2="13"/><line x1="19" y1="7" x2="14" y2="13"/></svg>';const btn=document.getElementById("muteBtn"),label=typeof LT==="function"?LT("SES","SFX","SONIDO","SOUND","AUDIO"):(typeof LANG!=="undefined"&&LANG==="tr"?"SES":"SFX");if(btn)btn.innerHTML=(muted?_off:_on)+'<span id="muteBtnLbl">'+label+'</span>';}
function toggleMute(){muted=!muted;paintMuteButton();if(muted)crowdStop();else{ac();playUiSample("release",.15);}}

/* Effects are opt-in after the first interaction and the preference survives a refresh. */
const _toggleMuteBase=toggleMute;
toggleMute=function(){_toggleMuteBase();try{localStorage.setItem("copa_sfx",muted?"0":"1");}catch(e){}const b=document.getElementById("muteBtn");if(b){b.classList.toggle("on",!muted);b.setAttribute("aria-pressed",String(!muted));}};
(()=>{try{const saved=localStorage.getItem("copa_sfx");muted=saved==="0";if(saved===null){muted=false;localStorage.setItem("copa_sfx","1");}}catch(e){muted=false;}paintMuteButton();const b=document.getElementById("muteBtn");if(b){b.classList.toggle("on",!muted);b.setAttribute("aria-pressed",String(!muted));}})();
function sfxCoin(){if(playUiSample("buy",.21))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;[988,1319,1760].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.setValueAtTime(f,t+i*0.05);g.gain.setValueAtTime(0.0001,t+i*0.05);g.gain.exponentialRampToValueAtTime(0.035,t+i*0.05+0.01);g.gain.exponentialRampToValueAtTime(0.0001,t+i*0.05+0.18);o.connect(g);g.connect(c.destination);o.start(t+i*0.05);o.stop(t+i*0.05+0.2);});}
function sfxGrumble(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain(),lfo=c.createOscillator(),lg=c.createGain();o.type="sawtooth";o.frequency.value=82;lfo.type="sine";lfo.frequency.value=6.5;lg.gain.value=13;lfo.connect(lg);lg.connect(o.frequency);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.04,t+0.05);g.gain.setValueAtTime(0.03,t+0.35);g.gain.exponentialRampToValueAtTime(0.0001,t+0.6);o.connect(g);g.connect(c.destination);o.start(t);lfo.start(t);o.stop(t+0.62);lfo.stop(t+0.62);}
function sfxJingle(){if(playUiSample("reward",.21))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;[523,659,784,1047].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.value=f;g.gain.setValueAtTime(0.0001,t+i*0.08);g.gain.exponentialRampToValueAtTime(0.025,t+i*0.08+0.01);g.gain.exponentialRampToValueAtTime(0.0001,t+i*0.08+0.22);o.connect(g);g.connect(c.destination);o.start(t+i*0.08);o.stop(t+i*0.08+0.24);});}
function sfxFlag(country){
  const key="flag_"+String(country||"IT").toUpperCase();
  playUiSample(UI_SFX[key]?key:"flag_IT",.32,90);
}
function sfxFormation(){return sfxFlag("IT");}
function sfxTalk(k){playUiSample("talk_"+k,.38);}
function sfxSave(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const src=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();src.buffer=noiseBuf(c,0.04);f.type="bandpass";f.frequency.value=600;g.gain.setValueAtTime(0.022,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.07);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);}
function sfxEndResult(won,endType){if(typeof muted!=="undefined"&&muted)return;if(won)playUiSample("championship",.38);else if(endType==="sacked")playUiSample("kickedout",.38);else playUiSample("eliminated",.58);}
function sfxPass(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.setValueAtTime(380,t);o.frequency.exponentialRampToValueAtTime(220,t+0.06);g.gain.setValueAtTime(0.018,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.09);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.1);}
function sfxPost(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.setValueAtTime(1400,t);o.frequency.exponentialRampToValueAtTime(900,t+0.12);g.gain.setValueAtTime(0.03,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.18);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.2);}
function sfxArena(outcome){if(muted)return false;const c=ac();if(!c)return false;const t=c.currentTime;if(outcome==="goal")sfxGoal();else if(outcome==="save"){sfxSave();click(c,t+.03,180,.045,.2);}else if(outcome==="post"){sfxPost();click(c,t+.03,2100,.025,.28);}else{sfxPass();click(c,t,260,.025,.32);}return true;}
function sfxArenaTick(tock,urgent){if(muted)return;const c=ac();if(c)click(c,c.currentTime,tock?760:1200,urgent?.022:.014,tock?.055:.038);}
function sfxArenaFound(){if(muted)return false;const c=ac();if(!c)return false;const t=c.currentTime;[523,659,784,1047,1319].forEach((frequency,index)=>{const oscillator=c.createOscillator(),gain=c.createGain(),at=t+index*.065;oscillator.type=index<3?"triangle":"sine";oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.035,at+.018);gain.gain.exponentialRampToValueAtTime(.0001,at+.28);oscillator.connect(gain);gain.connect(c.destination);oscillator.start(at);oscillator.stop(at+.3);});return true;}
function sfxGoal(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;/* crowd roar */const src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=noiseBuf(c,1.4);src.loop=true;f.type="bandpass";f.frequency.value=480;f.Q.value=0.6;g.gain.setValueAtTime(0.001,t);g.gain.linearRampToValueAtTime(0.065,t+0.18);g.gain.setValueAtTime(0.055,t+0.9);g.gain.exponentialRampToValueAtTime(0.001,t+1.4);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);src.stop(t+1.5);/* fanfare */[0,0.14,0.28,0.42].forEach((dt,i)=>{const freq=[659,784,988,1319][i];const o2=c.createOscillator(),g2=c.createGain();o2.type="triangle";o2.frequency.value=freq;g2.gain.setValueAtTime(0.001,t+dt);g2.gain.linearRampToValueAtTime(0.04,t+dt+0.06);g2.gain.exponentialRampToValueAtTime(0.001,t+dt+0.28);o2.connect(g2);g2.connect(c.destination);o2.start(t+dt);o2.stop(t+dt+0.3);});}
function sfxInjury(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;/* thud */const src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=noiseBuf(c,0.12);f.type="lowpass";f.frequency.value=160;g.gain.setValueAtTime(0.07,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.12);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);/* low groan */const o=c.createOscillator(),g2=c.createGain();o.type="sine";o.frequency.setValueAtTime(140,t+0.06);o.frequency.exponentialRampToValueAtTime(80,t+0.4);g2.gain.setValueAtTime(0.001,t+0.06);g2.gain.linearRampToValueAtTime(0.022,t+0.12);g2.gain.exponentialRampToValueAtTime(0.001,t+0.4);o.connect(g2);g2.connect(c.destination);o.start(t+0.06);o.stop(t+0.42);}
function sfxCard(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;/* quick sharp swipe */const src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=noiseBuf(c,0.05);f.type="highpass";f.frequency.value=3200;g.gain.setValueAtTime(0.035,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.05);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);click(c,t+0.04,880,0.022,0.06);}
function sfxDrawPick(){if(typeof muted!=="undefined"&&muted)return;const c=ac();if(!c)return;const t=c.currentTime;[260,330,410].forEach((f,i)=>click(c,t+i*.045,f,.022,.045));}
function sfxDrawPlace(isPlayer){if(typeof muted!=="undefined"&&muted)return;const c=ac();if(!c)return;const t=c.currentTime;click(c,t,isPlayer?760:610,.035,.07);click(c,t+.055,isPlayer?1080:820,.022,.09);}
function sfxDrawComplete(){if(typeof muted!=="undefined"&&muted)return;const c=ac();if(!c)return;const t=c.currentTime;[523,659,784,1047].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),at=t+i*.085;o.type="triangle";o.frequency.value=f;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.028,at+.012);g.gain.exponentialRampToValueAtTime(.0001,at+.22);o.connect(g);g.connect(c.destination);o.start(at);o.stop(at+.24);});}
