/* Ses efektleri: Kenney UI audio + Web Audio fallback, zar, alkis, duduk, kalabalik, mute. */
let AC=null,crowdNodes=null;
const UI_SFX={
 click:"assets/audio/ui/click1.ogg",stamp:"assets/audio/ui/click3.ogg",
 select:"assets/audio/ui/mouseclick1.ogg",release:"assets/audio/ui/mouserelease1.ogg",
 hover:"assets/audio/ui/rollover2.ogg",switch:"assets/audio/ui/switch10.ogg",
 buy:"assets/audio/ui/switch23.ogg",reward:"assets/audio/ui/switch33.ogg",
 championship:"assets/audio/ui/championship.ogg",eliminated:"assets/audio/ui/eliminated.ogg",
 kickedout:"assets/audio/ui/kickedout.ogg",
 flag_TR:"assets/audio/ui/turkiye.ogg",flag_IT:"assets/audio/ui/switch33.ogg",
 flag_ENG:"assets/audio/ui/england.ogg",flag_ES:"assets/audio/ui/spain.ogg",
 flag_DE:"assets/audio/ui/germany.ogg",
 talk_gaz:"assets/audio/ui/atesle.ogg",talk_mantik:"assets/audio/ui/planihatirlat.ogg",
 talk_sert:"assets/audio/ui/disiplin.ogg"
};
function playUiSample(k,vol){if(typeof muted!=="undefined"&&muted)return false;const src=UI_SFX[k];if(!src)return false;try{const a=new Audio(src);a.volume=vol==null?.22:vol;const p=a.play();if(p&&p.catch)p.catch(()=>{});return true;}catch(e){return false;}}
function ac(){if(!AC){try{AC=new (window.AudioContext||window.webkitAudioContext)();}catch(e){}}return AC;}
function noiseBuf(c,dur){const n=Math.floor(c.sampleRate*dur),b=c.createBuffer(1,n,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=Math.random()*2-1;return b;}
function click(c,t,f,v,du){const o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.value=f;g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(v,t+0.004);g.gain.exponentialRampToValueAtTime(0.0001,t+du);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+du+0.01);}
function sfxRoll(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;let tt=0;for(let i=0;i<14;i++){click(c,t+tt,ri(160,360),0.03,0.03);tt+=0.03+i*0.006;}const src=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();src.buffer=noiseBuf(c,0.5);f.type="bandpass";f.frequency.value=900;g.gain.setValueAtTime(0.025,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.5);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);}
function sfxTick(){if(playUiSample("hover",.11))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;for(let i=0;i<3;i++)click(c,t+i*0.12,1200-i*200,0.025,0.04);}
function sfxSeat(){if(playUiSample("select",.18))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.setValueAtTime(220,t);o.frequency.exponentialRampToValueAtTime(90,t+0.07);g.gain.setValueAtTime(0.06,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.1);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.11);click(c,t+0.02,520,0.025,0.02);}
function sfxStamp(){if(playUiSample("stamp",.17))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.setValueAtTime(170,t);o.frequency.exponentialRampToValueAtTime(55,t+0.12);g.gain.setValueAtTime(0.065,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.18);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.2);}
function sfxWhistle(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.setValueAtTime(1750,t);g.gain.setValueAtTime(0.001,t);g.gain.linearRampToValueAtTime(0.025,t+0.03);g.gain.setValueAtTime(0.025,t+0.16);g.gain.exponentialRampToValueAtTime(0.0001,t+0.28);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.3);}
function sfxKick(power){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const src=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();src.buffer=noiseBuf(c,0.06);f.type="bandpass";f.frequency.value=power>5?260:380;g.gain.setValueAtTime(power>5?0.04:0.018,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.06);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);}
function crowdStart(){if(muted||!ac())return;const c=AC;const src=c.createBufferSource();src.buffer=noiseBuf(c,2);src.loop=true;const f=c.createBiquadFilter();f.type="lowpass";f.frequency.value=520;const g=c.createGain();g.gain.value=0.014;src.connect(f);f.connect(g);g.connect(c.destination);src.start();crowdNodes={src,g};}
function crowdStop(){if(crowdNodes){try{crowdNodes.src.stop();}catch(e){}crowdNodes=null;}}
function crowdSwell(){if(!crowdNodes)return;const c=AC,t=c.currentTime,g=crowdNodes.g.gain;g.cancelScheduledValues(t);g.setValueAtTime(0.014,t);g.linearRampToValueAtTime(0.06,t+0.1);g.exponentialRampToValueAtTime(0.014,t+1.2);}
function toggleMute(){muted=!muted;const _on='<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" width="14" height="14"><polygon points="2,7 6,7 11,3 11,17 6,13 2,13" fill="currentColor" stroke-linejoin="round"/><path d="M13.5 7.5Q15.5 10 13.5 12.5"/><path d="M16 5.5Q19 10 16 14.5"/></svg>';const _off='<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" width="14" height="14"><polygon points="2,7 6,7 11,3 11,17 6,13 2,13" fill="currentColor" stroke-linejoin="round"/><line x1="14" y1="7" x2="19" y2="13"/><line x1="19" y1="7" x2="14" y2="13"/></svg>';const btn=$("muteBtn");if(btn)btn.innerHTML=muted?_off:_on;if(muted)crowdStop();else{ac();playUiSample("release",.15);}}
function sfxCoin(){if(playUiSample("buy",.21))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;[988,1319,1760].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.setValueAtTime(f,t+i*0.05);g.gain.setValueAtTime(0.0001,t+i*0.05);g.gain.exponentialRampToValueAtTime(0.035,t+i*0.05+0.01);g.gain.exponentialRampToValueAtTime(0.0001,t+i*0.05+0.18);o.connect(g);g.connect(c.destination);o.start(t+i*0.05);o.stop(t+i*0.05+0.2);});}
function sfxGrumble(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain(),lfo=c.createOscillator(),lg=c.createGain();o.type="sawtooth";o.frequency.value=82;lfo.type="sine";lfo.frequency.value=6.5;lg.gain.value=13;lfo.connect(lg);lg.connect(o.frequency);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.04,t+0.05);g.gain.setValueAtTime(0.03,t+0.35);g.gain.exponentialRampToValueAtTime(0.0001,t+0.6);o.connect(g);g.connect(c.destination);o.start(t);lfo.start(t);o.stop(t+0.62);lfo.stop(t+0.62);}
function sfxJingle(){if(playUiSample("reward",.21))return;if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;[523,659,784,1047].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.value=f;g.gain.setValueAtTime(0.0001,t+i*0.08);g.gain.exponentialRampToValueAtTime(0.025,t+i*0.08+0.01);g.gain.exponentialRampToValueAtTime(0.0001,t+i*0.08+0.22);o.connect(g);g.connect(c.destination);o.start(t+i*0.08);o.stop(t+i*0.08+0.24);});}
function sfxFlag(country){playUiSample("flag_"+country,.35);}
function sfxTalk(k){playUiSample("talk_"+k,.38);}
function sfxSave(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const src=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();src.buffer=noiseBuf(c,0.04);f.type="bandpass";f.frequency.value=600;g.gain.setValueAtTime(0.022,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.07);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t);}
function sfxEndResult(won,endType){if(typeof muted!=="undefined"&&muted)return;if(won)playUiSample("championship",.38);else if(endType==="sacked")playUiSample("kickedout",.38);else playUiSample("eliminated",.38);}
function sfxPass(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.setValueAtTime(380,t);o.frequency.exponentialRampToValueAtTime(220,t+0.06);g.gain.setValueAtTime(0.018,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.09);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.1);}
function sfxPost(){if(muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.setValueAtTime(1400,t);o.frequency.exponentialRampToValueAtTime(900,t+0.12);g.gain.setValueAtTime(0.03,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.18);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+0.2);}
