/* Yan Saha route, localized insight surface and atomic game-economy adapter. */
(function(root){
  "use strict";
  let view="round",draft=null;
  const trackedMarkets=new Set();
  const COPY={
    tr:{noMarket:"PİYASA YOK",groups:"GRUPLAR",matchday:"MAÇ GÜNÜ",r16:"SON 16",qf:"ÇEYREK FİNAL",sf:"YARI FİNAL",final:"FİNAL",open:"AÇIK",locked:"KİLİTLİ",settled:"SONUÇLANDI",draw:"BERABERLİK",saved:"SEÇİM YAPILDI",pre:"MAÇ ÖNCESİ",hit:"İSABET",miss:"KAÇTI",pending:"BEKLİYOR",roundRisk:"TUR BÜTÇESİ",left:"KULLANILABİLİR",noFixture:"Bu turda yan maç yok.",ownExcluded:"Kendi maçın tahmin piyasasına dahil edilmez.",noOther:"Bu turda başka maç yok.",noResult:"Henüz kehanet mühürlenmedi.",resultHint:"Maç gününün ardından tüm yan saha sonuçları burada görünür.",noPick:"Henüz seçim yapmadın.",pickHint:"Bir maç ve sonuç seç; riski onayladığında seçimin mühürlensin.",pick:"Yan Saha seçimi",close:"Kapat",slip:"KEHANET FİŞİ",odds:"ORAN",risk:"RİSK",possible:"OLASI DÖNÜŞ",seal:"SEÇİMİ MÜHÜRLE",limitWarn:"Bu seçim şu anda kullanılamıyor.",alreadySelected:"Bu maç için seçim yaptın.",fine:"Yalnızca oyun içi kulüp kasası · gerçek para değeri yoktur",clubCash:"KULÜP KASASI",tagline:"Kader çizilmez. Okunur, tartılır, göze alınır.",thisRound:"BU TUR",results:"SONUÇLAR",myPicks:"SEÇİMLERİM",protocol:"RİSK PROTOKOLÜ",protocolText:"Tekli seçim · €2M garanti · kasayla €5M'a kadar · başkan borç çizgisi · kendi maçın hariç",form:"FORM",power:"GÜÇ FARKI",confidence:"GÜVEN",high:"YÜKSEK",medium:"ORTA",balanced:"DENGELİ",record:"KEHANET KAYDI",net:"NET",rate:"İSABET",streak:"SERİ",home:"EV",away:"DEP",sealed:"Seçim mühürlendi",settledFeed:"Yan Saha seçimleri sonuçlandı",hitFeed:"Yan Saha isabeti"},
    en:{noMarket:"NO MARKET",groups:"GROUPS",matchday:"MATCHDAY",r16:"ROUND OF 16",qf:"QUARTERFINAL",sf:"SEMIFINAL",final:"FINAL",open:"OPEN",locked:"LOCKED",settled:"SETTLED",draw:"DRAW",saved:"PICK SAVED",pre:"PRE-MATCH",hit:"HIT",miss:"MISS",pending:"PENDING",roundRisk:"ROUND BUDGET",left:"AVAILABLE",noFixture:"No side fixture this round.",ownExcluded:"Your own match is never included.",noOther:"There are no other fixtures this round.",noResult:"No prophecy has been sealed yet.",resultHint:"All side-fixture results appear here after matchday.",noPick:"You have no picks yet.",pickHint:"Choose a fixture and outcome, then seal your risk.",pick:"Side Field pick",close:"Close",slip:"PROPHECY SLIP",odds:"ODDS",risk:"RISK",possible:"POSSIBLE RETURN",seal:"SEAL PICK",limitWarn:"This pick is currently unavailable.",alreadySelected:"You already picked this fixture.",fine:"In-game club funds only · no real-money value",clubCash:"CLUB CASH",tagline:"Fate is read, weighed and risked.",thisRound:"THIS ROUND",results:"RESULTS",myPicks:"MY PICKS",protocol:"RISK PROTOCOL",protocolText:"Singles only · €2M guaranteed · up to €5M with cash · chairman debt line · excludes your match",form:"FORM",power:"POWER GAP",confidence:"CONFIDENCE",high:"HIGH",medium:"MEDIUM",balanced:"BALANCED",record:"PROPHECY RECORD",net:"NET",rate:"HIT RATE",streak:"STREAK",home:"HOME",away:"AWAY",sealed:"Pick sealed",settledFeed:"Side Field picks settled",hitFeed:"Side Field hit"},
    es:{noMarket:"SIN MERCADO",groups:"GRUPOS",matchday:"JORNADA",r16:"OCTAVOS",qf:"CUARTOS",sf:"SEMIFINAL",final:"FINAL",open:"ABIERTO",locked:"CERRADO",settled:"RESUELTO",draw:"EMPATE",saved:"ELECCIÓN GUARDADA",pre:"PREVIA",hit:"ACIERTO",miss:"FALLO",pending:"PENDIENTE",roundRisk:"PRESUPUESTO DE RONDA",left:"DISPONIBLE",noFixture:"No hay partidos paralelos esta ronda.",ownExcluded:"Tu propio partido nunca se incluye.",noOther:"No hay otros partidos esta ronda.",noResult:"Aún no hay profecías selladas.",resultHint:"Los resultados aparecerán después de la jornada.",noPick:"Aún no has elegido.",pickHint:"Elige un partido y un resultado, y sella el riesgo.",pick:"Elección de Campo Lateral",close:"Cerrar",slip:"FICHA DE PROFECÍA",odds:"CUOTA",risk:"RIESGO",possible:"RETORNO POSIBLE",seal:"SELLAR ELECCIÓN",limitWarn:"Esta elección no está disponible ahora.",alreadySelected:"Ya elegiste este partido.",fine:"Solo fondos del club del juego · sin valor monetario real",clubCash:"CAJA DEL CLUB",tagline:"El destino se lee, se pesa y se arriesga.",thisRound:"ESTA RONDA",results:"RESULTADOS",myPicks:"MIS ELECCIONES",protocol:"PROTOCOLO DE RIESGO",protocolText:"Elecciones simples · €2M garantizados · hasta €5M según caja · límite del presidente · tu partido excluido",form:"FORMA",power:"DIFERENCIA",confidence:"CONFIANZA",high:"ALTA",medium:"MEDIA",balanced:"EQUILIBRADA",record:"REGISTRO",net:"NETO",rate:"ACIERTOS",streak:"RACHA",home:"LOCAL",away:"VIS.",sealed:"Elección sellada",settledFeed:"Elecciones de Campo Lateral resueltas",hitFeed:"Acierto de Campo Lateral"},
    de:{noMarket:"KEIN MARKT",groups:"GRUPPEN",matchday:"SPIELTAG",r16:"ACHTELFINALE",qf:"VIERTELFINALE",sf:"HALBFINALE",final:"FINALE",open:"OFFEN",locked:"GESPERRT",settled:"ABGERECHNET",draw:"REMIS",saved:"TIPP GESPEICHERT",pre:"VOR DEM SPIEL",hit:"TREFFER",miss:"DANEBEN",pending:"OFFEN",roundRisk:"RUNDENBUDGET",left:"VERFÜGBAR",noFixture:"Keine Nebenspiele in dieser Runde.",ownExcluded:"Dein eigenes Spiel ist ausgeschlossen.",noOther:"Keine weiteren Spiele in dieser Runde.",noResult:"Noch keine Prophezeiung besiegelt.",resultHint:"Alle Ergebnisse erscheinen nach dem Spieltag.",noPick:"Du hast noch keinen Tipp.",pickHint:"Wähle Spiel und Ergebnis und besiegle das Risiko.",pick:"Nebenplatz-Tipp",close:"Schließen",slip:"PROPHEZEIUNG",odds:"QUOTE",risk:"RISIKO",possible:"MÖGLICHE RÜCKKEHR",seal:"TIPP BESIEGELN",limitWarn:"Dieser Tipp ist derzeit nicht verfügbar.",alreadySelected:"Für dieses Spiel hast du bereits getippt.",fine:"Nur Spielgeld des Clubs · kein Echtgeldwert",clubCash:"CLUBKASSE",tagline:"Schicksal wird gelesen, gewogen und riskiert.",thisRound:"DIESE RUNDE",results:"ERGEBNISSE",myPicks:"MEINE TIPPS",protocol:"RISIKOPROTOKOLL",protocolText:"Einzeltipps · €2M garantiert · mit Kasse bis €5M · Schuldenlinie des Präsidenten · eigenes Spiel ausgeschlossen",form:"FORM",power:"STÄRKEABSTAND",confidence:"SICHERHEIT",high:"HOCH",medium:"MITTEL",balanced:"AUSGEGLICHEN",record:"BILANZ",net:"NETTO",rate:"TREFFER",streak:"SERIE",home:"HEIM",away:"GAST",sealed:"Tipp besiegelt",settledFeed:"Nebenplatz-Tipps abgerechnet",hitFeed:"Nebenplatz-Treffer"},
    it:{noMarket:"NESSUN MERCATO",groups:"GIRONI",matchday:"GIORNATA",r16:"OTTAVI",qf:"QUARTI",sf:"SEMIFINALE",final:"FINALE",open:"APERTO",locked:"BLOCCATO",settled:"RISOLTO",draw:"PAREGGIO",saved:"SCELTA SALVATA",pre:"PRE-PARTITA",hit:"PRESA",miss:"MANCATA",pending:"IN ATTESA",roundRisk:"BUDGET TURNO",left:"DISPONIBILE",noFixture:"Nessuna partita laterale in questo turno.",ownExcluded:"La tua partita non viene mai inclusa.",noOther:"Non ci sono altre partite in questo turno.",noResult:"Nessuna profezia ancora sigillata.",resultHint:"I risultati appariranno dopo la giornata.",noPick:"Non hai ancora scelto.",pickHint:"Scegli partita e risultato, poi sigilla il rischio.",pick:"Scelta Campo Laterale",close:"Chiudi",slip:"SCHEDA DELLA PROFEZIA",odds:"QUOTA",risk:"RISCHIO",possible:"RITORNO POSSIBILE",seal:"SIGILLA SCELTA",limitWarn:"Questa scelta non è disponibile ora.",alreadySelected:"Hai già scelto questa partita.",fine:"Solo fondi del club nel gioco · nessun valore reale",clubCash:"CASSA CLUB",tagline:"Il destino si legge, si pesa e si rischia.",thisRound:"QUESTO TURNO",results:"RISULTATI",myPicks:"LE MIE SCELTE",protocol:"PROTOCOLLO RISCHIO",protocolText:"Scelte singole · €2M garantiti · fino a €5M con la cassa · limite del presidente · tua partita esclusa",form:"FORMA",power:"DIVARIO",confidence:"FIDUCIA",high:"ALTA",medium:"MEDIA",balanced:"EQUILIBRATA",record:"REGISTRO",net:"NETTO",rate:"PRECISIONE",streak:"SERIE",home:"CASA",away:"OSP.",sealed:"Scelta sigillata",settledFeed:"Scelte Campo Laterale risolte",hitFeed:"Pronostico Campo Laterale preso"}
  };
  const c=()=>COPY[root.LANG]||COPY.en;
  const engine=()=>root.CopaSideFieldEngine;
  const esc=value=>String(value==null?"":value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const state=()=>{root.sideFieldState=engine().normalizeState(root.sideFieldState);return root.sideFieldState;};
  const cash=()=>Number(root.budget)||0;
  const amount=value=>{const rounded=Math.round((Number(value)||0)*2)/2;return Number.isInteger(rounded)?String(rounded):rounded.toFixed(1);};
  const money=value=>`${Number(value)<0?"−":""}€${amount(Math.abs(Number(value)||0))}M`;
  const debtFloor=()=>Number(typeof root.activeDebtLimit==="function"?root.activeDebtLimit():engine().DEFAULT_CASH_FLOOR);
  const track=(event,properties)=>root.CopaAnalytics&&root.CopaAnalytics.track(event,properties||{});
  function journal(){root.runTransactionJournal=root.CopaRunJournal?root.CopaRunJournal.normalizeState(root.runTransactionJournal):null;return root.runTransactionJournal;}
  function committed(id){return !!(root.CopaRunJournal&&root.CopaRunJournal.isCommitted(journal(),id));}
  function begin(id,kind,payload){if(!root.CopaRunJournal)return true;const result=root.CopaRunJournal.begin(journal(),{id,kind,round:Number(root.round)||0,payload});root.runTransactionJournal=result.state;return result.ok;}
  function commit(id){if(!root.CopaRunJournal)return;root.runTransactionJournal=root.CopaRunJournal.commit(journal(),id).state;}
  function snapshot(){return JSON.parse(JSON.stringify(state()));}
  function restore(value){root.sideFieldState=engine().normalizeState(value);draft=null;return state();}
  function reset(){root.sideFieldState=engine().createState();draft=null;}
  function ensureCurrent(){
    if(!engine()||!root.tournament)return null;
    const result=engine().ensureMarket(state(),root.tournament,cash());root.sideFieldState=result.state;
    if(result.market&&!trackedMarkets.has(result.market.key)){trackedMarkets.add(result.market.key);track("sidefield_opened",{stage:result.market.stage==="group"?"group":result.market.round,group_matchday:result.market.matchday||0,economy_band:root.analyticsEconomyBand?root.analyticsEconomyBand(cash()):""});}
    return result.market;
  }
  function currentKey(){const market=ensureCurrent();return market&&market.key||"";}
  function score(match){return match&&match.status==="played"&&Array.isArray(match.score)?`${match.score[0]}–${match.score[1]}`:"";}
  function initials(name){return String(name||"?").split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toLocaleUpperCase().slice(0,2);}
  function stageLabel(market){if(!market)return c().noMarket;if(market.stage==="group")return `${c().groups} · ${market.matchday}. ${c().matchday}`;return({roundof16:c().r16,quarterfinal:c().qf,semifinal:c().sf,final:c().final})[market.round]||String(market.round||"").toUpperCase();}
  function statusLabel(status){return({open:c().open,locked:c().locked,settled:c().settled})[status]||status;}
  function pickLabel(pick,quote){if(pick==="D")return c().draw;return pick==="H"?quote.homeName:quote.awayName;}
  function usedRisk(market){return market?engine().exposure(state(),market).used:0;}
  function availableStake(market,odds){if(!market)return[];const exposure=engine().exposure(state(),market),minimum=engine().minStakeForOdds(odds),max=Math.min(exposure.remaining,engine().maxStakeForOdds(odds),Math.max(0,Math.floor(cash()-debtFloor())));return Array.from({length:Math.max(0,max-minimum+1)},(_,index)=>minimum+index);}
  function formText(form){return form&&form.played?`${form.points}/${form.played*3}`:"—";}
  function insightLine(quote){const intel=quote.intel||{},gap=Number(intel.powerGap)||0,leader=gap===0?"—":gap>0?`${c().home} +${gap}`:`${c().away} +${Math.abs(gap)}`,confidence=c()[intel.confidence]||c().balanced;return `<div class="ys-insight"><span><small>${c().power}</small><b>${leader}</b></span><span><small>${c().form}</small><b>${formText(intel.homeForm)} · ${formText(intel.awayForm)}</b></span><span><small>${c().confidence}</small><b>${confidence}</b></span></div>`;}
  function ticketLine(ticket,quote){const tone=ticket.status==="won"?"win":ticket.status==="lost"?"loss":"open",label=ticket.status==="won"?c().hit:ticket.status==="lost"?c().miss:ticket.status==="locked"?c().locked:c().pending;return `<div class="ys-ticket-line ${tone}"><span>${esc(pickLabel(ticket.pick,quote))} · ${ticket.odds.toFixed(2)}</span><b>${label}${ticket.status==="won"?` · +€${ticket.payout}M`:""}</b></div>`;}
  function marketCard(market,quote){const match=root.tournament&&root.tournament.matches&&root.tournament.matches[quote.matchId],played=match&&match.status==="played",existing=engine().roundTickets(state(),market.key).find(ticket=>ticket.matchId===quote.matchId),picks=market.stage==="group"?["H","D","A"]:["H","A"];return `<article class="ys-match-card ${played?"is-played":""} ${existing?"has-ticket":""}"><div class="ys-match-meta"><span>${market.stage==="group"?`#${esc(match&&match.groupId||"")}`:stageLabel(market)}</span>${played?`<b>${score(match)}</b>`:`<i>${existing?c().saved:c().pre}</i>`}</div><div class="ys-teams"><span><i>${esc(initials(quote.homeName))}</i><b>${esc(quote.homeName)}</b></span><em>${played?score(match):"VS"}</em><span><i>${esc(initials(quote.awayName))}</i><b>${esc(quote.awayName)}</b></span></div>${insightLine(quote)}<div class="ys-odds">${picks.map(pick=>`<button type="button" ${market.status!=="open"||played||existing?"disabled":""} onclick="CopaSideField.select('${esc(quote.matchId)}','${pick}')"><span>${pick==="H"?"1":pick==="D"?"X":"2"}</span><b>${quote.odds[pick].toFixed(2)}</b></button>`).join("")}</div>${existing?`${ticketLine(existing,quote)}<p class="ys-unavailable-reason">${c().alreadySelected}</p>`:""}</article>`;}
  function recordPanel(){const metrics=engine().metrics(state());return `<section class="ys-record" aria-label="${c().record}"><b>${c().record}</b><span><small>${c().net}</small><strong class="${metrics.net>=0?"win":"loss"}">${metrics.net>=0?"+":""}${money(metrics.net)}</strong></span><span><small>${c().rate}</small><strong>${metrics.settled?Math.round(metrics.hitRate*100)+"%":"—"}</strong></span><span><small>${c().streak}</small><strong>${metrics.currentStreak}</strong></span></section>`;}
  function roundPanel(market){if(!market)return `<div class="ys-empty"><b>${c().noFixture}</b><p>${c().ownExcluded}</p></div>`;const exposure=engine().exposure(state(),market);return `${recordPanel()}<div class="ys-risk-strip is-${exposure.level}"><span><small>${c().roundRisk}</small><b>€${exposure.used}M / €${exposure.limit}M</b></span><i><em style="width:${exposure.ratio*100}%"></em></i><span><small>${c().left}</small><b>€${exposure.remaining}M</b></span></div><div class="ys-match-grid">${market.quotes.map(quote=>marketCard(market,quote)).join("")||`<div class="ys-empty"><b>${c().noOther}</b></div>`}</div>`;}
  function ticketResultFor(match,market){const ticket=engine().roundTickets(state(),market.key).find(item=>item.matchId===match.id);return ticket?`<strong class="${ticket.status}">${ticket.status==="won"?`+€${ticket.payout}M`:ticket.status==="lost"?`−€${ticket.stake}M`:c().pending}</strong>`:"<strong>—</strong>";}
  function resultsPanel(){const rows=[];for(const market of Object.values(state().markets).slice().reverse())for(const quote of market.quotes){const match=root.tournament&&root.tournament.matches&&root.tournament.matches[quote.matchId];if(match&&match.status==="played")rows.push(`<article><span><small>${stageLabel(market)}</small><b>${esc(quote.homeName)} <em>${score(match)}</em> ${esc(quote.awayName)}</b></span>${ticketResultFor(match,market)}</article>`);}return rows.length?`${recordPanel()}<div class="ys-results-list">${rows.join("")}</div>`:`<div class="ys-empty"><b>${c().noResult}</b><p>${c().resultHint}</p></div>`;}
  function ticketsPanel(){const tickets=state().tickets.slice().reverse();if(!tickets.length)return `<div class="ys-empty"><b>${c().noPick}</b><p>${c().pickHint}</p></div>`;return `${recordPanel()}<div class="ys-my-tickets">${tickets.map(ticket=>{const market=state().markets[ticket.marketKey],quote=market&&market.quotes.find(item=>item.matchId===ticket.matchId);if(!quote)return"";const label=ticket.status==="won"?c().hit:ticket.status==="lost"?c().miss:ticket.status==="locked"?c().locked:c().pending;return`<article class="${ticket.status}"><span>${stageLabel(market)}</span><h3>${esc(quote.homeName)} — ${esc(quote.awayName)}</h3><p>${esc(pickLabel(ticket.pick,quote))} · ${ticket.odds.toFixed(2)}</p><div><b>€${ticket.stake}M</b><em>→</em><strong>€${ticket.potentialPayout}M</strong></div><small>${label}</small></article>`;}).join("")}</div>`;}
  function draftPanel(market){if(!draft||!market)return"";const quote=market.quotes.find(item=>item.matchId===draft.matchId);if(!quote){draft=null;return"";}const odds=quote.odds[draft.pick],stakes=availableStake(market,odds),selected=stakes.includes(draft.stake)?draft.stake:(stakes[0]||0),blocked=stakes.length?null:engine().canPlace(state(),market,draft.matchId,draft.pick,1,cash(),debtFloor());draft.stake=selected;return `<div class="ys-slip-backdrop" onclick="if(event.target===this)CopaSideField.closeSlip()"><aside class="ys-slip" role="dialog" aria-modal="true" aria-label="${c().pick}"><button class="ys-slip-close" onclick="CopaSideField.closeSlip()" aria-label="${c().close}">×</button><span>${c().slip}</span><h2>${esc(quote.homeName)} — ${esc(quote.awayName)}</h2><p>${esc(pickLabel(draft.pick,quote))}</p>${insightLine(quote)}<div class="ys-slip-odds"><small>${c().odds}</small><b>${odds.toFixed(2)}</b></div>${stakes.length?`<label>${c().risk}</label><div class="ys-stakes">${stakes.map(value=>`<button class="${value===selected?"active":""}" onclick="CopaSideField.setStake(${value})">€${value}M</button>`).join("")}</div><div class="ys-slip-return"><span>${c().possible}</span><b>€${amount(engine().payoutFor(selected,odds))}M</b></div><button class="ys-seal" onclick="CopaSideField.place()">${c().seal}</button>`:`<div class="ys-slip-warning">${reasonText(blocked||{reason:"invalid_stake"})}</div>`}<small class="ys-fineprint">${c().fine}</small></aside></div>`;}
  function render(){const route=document.getElementById("sideFieldRoute");if(!route)return;const market=ensureCurrent();route.innerHTML=`<div class="ys-shell"><header class="ys-hero"><div><span>${stageLabel(market)}</span><h1>YAN SAHA</h1><p>${c().tagline}</p></div><aside><small>${c().clubCash}</small><b>${money(cash())}</b><em class="${market&&market.status||"settled"}">${statusLabel(market&&market.status||"settled")}</em></aside></header><nav class="ys-tabs"><button class="${view==="round"?"active":""}" onclick="CopaSideField.setView('round')">${c().thisRound}</button><button class="${view==="results"?"active":""}" onclick="CopaSideField.setView('results')">${c().results}</button><button class="${view==="tickets"?"active":""}" onclick="CopaSideField.setView('tickets')">${c().myPicks}<i>${state().tickets.length}</i></button></nav><main>${view==="results"?resultsPanel():view==="tickets"?ticketsPanel():roundPanel(market)}</main><footer><b>${c().protocol}</b><span>${c().protocolText}</span></footer></div>${draftPanel(market)}`;}
  function mount(){let route=document.getElementById("sideFieldRoute");if(!route){route=document.createElement("section");route.id="sideFieldRoute";route.className="side-field-route";document.getElementById("hub")?.appendChild(route);}render();return route;}
  function setView(next){view=["round","results","tickets"].includes(next)?next:"round";draft=null;track("sidefield_view_changed",{detail:view});render();}
  function select(matchId,pick){const market=ensureCurrent();if(!market||market.status!=="open")return;const quote=market.quotes.find(item=>item.matchId===matchId);draft={matchId,pick,stake:0};track("sidefield_selection_viewed",{stage:market.stage==="group"?"group":market.round,sidefield_pick:pick,confidence:quote&&quote.intel&&quote.intel.confidence||""});render();}
  function setStake(value){if(draft)draft.stake=Math.max(1,Math.floor(Number(value)||1));render();}
  function closeSlip(){draft=null;render();}
  function reasonText(result){const maps={
    tr:{market_closed:"Piyasa maça çıkışta kilitlenir.",selection_missing:"Bu seçim artık kullanılamıyor.",invalid_stake:"Geçerli bir risk seç.",ticket_limit:"Bu turdaki dört seçim hakkını kullandın.",match_already_selected:"Bu maç için seçim yaptın.",risk_limit:"Tur bütçesi doldu.",cash_reserve:"Başkanın borç çizgisine göre",payout_limit:"Bu oran için izin verilen dönüş tavanına ulaşıldı."},
    en:{market_closed:"The market locks at kickoff.",selection_missing:"This pick is no longer available.",invalid_stake:"Choose a valid risk.",ticket_limit:"You used all four picks this round.",match_already_selected:"You already picked this fixture.",risk_limit:"The round budget is full.",cash_reserve:"Based on the chairman's debt line",payout_limit:"The return cap for these odds has been reached."},
    es:{market_closed:"El mercado se cierra al comenzar el partido.",selection_missing:"Esta elección ya no está disponible.",invalid_stake:"Elige un riesgo válido.",ticket_limit:"Ya usaste las cuatro elecciones de esta ronda.",match_already_selected:"Ya elegiste este partido.",risk_limit:"El presupuesto de la ronda está completo.",cash_reserve:"Según el límite de deuda del presidente",payout_limit:"Se alcanzó el límite de retorno para esta cuota."},
    de:{market_closed:"Der Markt schließt beim Anpfiff.",selection_missing:"Dieser Tipp ist nicht mehr verfügbar.",invalid_stake:"Wähle ein gültiges Risiko.",ticket_limit:"Du hast alle vier Tipps dieser Runde genutzt.",match_already_selected:"Für dieses Spiel hast du bereits getippt.",risk_limit:"Das Rundenbudget ist ausgeschöpft.",cash_reserve:"Gemäß der Schuldenlinie des Präsidenten",payout_limit:"Das Rückkehrlimit für diese Quote ist erreicht."},
    it:{market_closed:"Il mercato si chiude al calcio d'inizio.",selection_missing:"Questa scelta non è più disponibile.",invalid_stake:"Scegli un rischio valido.",ticket_limit:"Hai usato tutte le quattro scelte del turno.",match_already_selected:"Hai già scelto questa partita.",risk_limit:"Il budget del turno è esaurito.",cash_reserve:"In base al limite debiti del presidente",payout_limit:"È stato raggiunto il limite di ritorno per questa quota."}
  };const map=maps[root.LANG]||maps.en;if(result.reason==="minimum_stake")return `${map.invalid_stake} €${result.minimum||1}M`;if(result.reason==="cash_reserve"){const missing=amount(result.shortfall||1),copy={tr:`€${missing}M eksik.`,en:`€${missing}M short.`,es:`Faltan €${missing}M.`,de:`€${missing}M fehlen.`,it:`Mancano €${missing}M.`};return copy[root.LANG]||copy.en;}return map[result.reason]||c().limitWarn;}
  function place(){
    const market=ensureCurrent();if(!draft||!market)return;const id=`sidefield:place:${market.key}:${draft.matchId}`;if(committed(id)){root.showToast?.(reasonText({reason:"match_already_selected"}));return;}
    const quote=market.quotes.find(item=>item.matchId===draft.matchId),result=engine().place(state(),market.key,draft.matchId,draft.pick,draft.stake,cash(),debtFloor());if(!result.ok){root.showToast?.(reasonText(result));return;}if(!begin(id,"sidefield_place",{marketKey:market.key,stake:result.ticket.stake,pick:result.ticket.pick}))return;
    root.sideFieldState=result.state;const stakeAmount=result.ticket.stake,before=cash();root.budget=Math.round((before-stakeAmount)*2)/2;if(root.econStats)root.econStats.yanSahaStaked=(root.econStats.yanSahaStaked||0)+stakeAmount;if(typeof root.recordCashFlow==="function")root.recordCashFlow("expense",stakeAmount,"yan_saha",before,root.budget,0);commit(id);
    track("sidefield_pick_placed",{stage:market.stage==="group"?"group":market.round,group_matchday:market.matchday||0,sidefield_pick:result.ticket.pick,stake_band:`m${stakeAmount}`,confidence:quote&&quote.intel&&quote.intel.confidence||"",economy_band:root.analyticsEconomyBand?root.analyticsEconomyBand(root.budget):""});draft=null;root.setBudget?.();root._saveState?.();root.showToast?.(`${c().sealed} · −€${stakeAmount}M`,{type:"info"});render();
  }
  function lockCurrent(){const market=ensureCurrent(),id=market?`sidefield:lock:${market.key}`:"";if(id&&committed(id))return{state:state(),count:0};const result=engine().lock(state(),root.tournament);root.sideFieldState=result.state;if(id){begin(id,"sidefield_lock",{marketKey:market.key});commit(id);}render();return result;}
  function settleMarket(marketKey){
    if(!marketKey)return{payout:0,settled:[]};const id=`sidefield:settle:${marketKey}`;if(committed(id))return{payout:0,settled:[]};const result=engine().settle(state(),root.tournament,marketKey);if(!result.settled.length)return result;begin(id,"sidefield_settle",{marketKey});root.sideFieldState=result.state;
    if(result.payout>0){root.earn?.(result.payout,"yanSahaPayout");if(root.econStats)root.econStats.yanSahaWon=(root.econStats.yanSahaWon||0)+result.payout;root.pushFeed?.(`✦ ${c().hitFeed}: +€${result.payout}M`,"win");}else root.pushFeed?.(`◇ ${c().settledFeed}`,"");commit(id);
    const won=result.settled.filter(ticket=>ticket.status==="won").length;track("sidefield_settled",{stage:state().markets[marketKey]&&state().markets[marketKey].stage||"",outcome:won?"win":"loss",detail:won&&won===result.settled.length?"all_hit":won?"mixed":"all_miss",economy_band:root.analyticsEconomyBand?root.analyticsEconomyBand(cash()):""});root.setBudget?.();root._saveState?.();render();return result;
  }
  root.CopaSideField={snapshot,restore,reset,ensureCurrent,currentKey,mount,render,setView,select,setStake,closeSlip,place,lockCurrent,settleMarket};
})(window);
