/* One canonical, localized contract for every card's visible effects. */
(function(root){
  "use strict";
  const TEXT={
    tr:{power:"GÜÇ",duration:"SÜRE",cost:"MALİYET",risk:"RİSK",source:"KAYNAK",none:"Yok",match:"Bu maç",next:"Sonraki maç",persistent:"Aktif kaldıkça",contract:"Sözleşme çözülene kadar",rounds:n=>`${n} tur`,market:"Kart Pazarı",card:"Kart sistemi",final:"Final cezası",chance:"olasılık",cash:"kasa",trust:"güven",chem:"kimya",price:"satın alma",burn:"kart yak",coupon:"kupon"},
    en:{power:"POWER",duration:"DURATION",cost:"COST",risk:"RISK",source:"SOURCE",none:"None",match:"This match",next:"Next match",persistent:"While equipped",contract:"Until contract resolves",rounds:n=>`${n} rounds`,market:"Card Market",card:"Card system",final:"Final penalty",chance:"chance",cash:"cash",trust:"trust",chem:"chemistry",price:"purchase",burn:"burn card",coupon:"coupon"},
    es:{power:"FUERZA",duration:"DURACIÓN",cost:"COSTE",risk:"RIESGO",source:"ORIGEN",none:"Ninguno",match:"Este partido",next:"Próximo partido",persistent:"Mientras esté activa",contract:"Hasta resolver el contrato",rounds:n=>`${n} rondas`,market:"Mercado de Cartas",card:"Sistema de cartas",final:"Penalización final",chance:"probabilidad",cash:"caja",trust:"confianza",chem:"química",price:"compra",burn:"quemar carta",coupon:"cupón"},
    de:{power:"STÄRKE",duration:"DAUER",cost:"KOSTEN",risk:"RISIKO",source:"QUELLE",none:"Keine",match:"Dieses Spiel",next:"Nächstes Spiel",persistent:"Solange aktiv",contract:"Bis der Vertrag endet",rounds:n=>`${n} Runden`,market:"Kartenmarkt",card:"Kartensystem",final:"Finalstrafe",chance:"Chance",cash:"Kasse",trust:"Vertrauen",chem:"Chemie",price:"Kauf",burn:"Karte opfern",coupon:"Gutschein"},
    it:{power:"FORZA",duration:"DURATA",cost:"COSTO",risk:"RISCHIO",source:"ORIGINE",none:"Nessuno",match:"Questa partita",next:"Prossima partita",persistent:"Finché attiva",contract:"Fino alla risoluzione",rounds:n=>`${n} turni`,market:"Mercato Carte",card:"Sistema carte",final:"Penalità finale",chance:"probabilità",cash:"cassa",trust:"fiducia",chem:"intesa",price:"acquisto",burn:"sacrifica carta",coupon:"buono"}
  };
  TEXT.tr.card="Kart etkisi";TEXT.en.card="Card effect";TEXT.es.card="Efecto de la carta";TEXT.de.card="Karteneffekt";TEXT.it.card="Effetto della carta";
  const t=()=>TEXT[root.LANG]||TEXT.en;
  const esc=value=>String(value==null?"":value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  function durationFor(key){const mode=typeof root.cardMode==="function"?root.cardMode(key):root.CARDDEFS&&root.CARDDEFS[key]&&root.CARDDEFS[key].mode;const fixed={gecici_prim:t().next,kisa_kamp:t().next,taksit_transfer:t().rounds(2),kumarbaz:t().rounds(2),nasip_kismet:t().rounds(2),primler_yatinca:t().next,vur_igneyi:t().match};return fixed[key]||(mode==="instant"?t().match:mode==="contract"?t().contract:t().persistent);}
  function riskFor(key,variant,meta){const risks=[];if(meta&&meta.risk)risks.push(`${meta.risk}% ${t().chance}${meta.cash?` · −€${meta.cash}M ${t().cash}`:""}`);const finalPenalty=variant===1&&root.KARA_PEN?Number(root.KARA_PEN[key]||0):0;if(finalPenalty)risks.push(`${t().final} −${finalPenalty}`);const purchase=root.DARK_PURCHASE_RISKS&&variant===1?root.DARK_PURCHASE_RISKS[key]:null;if(purchase&&!risks.some(line=>line.includes(`${Math.round(purchase.chance*100)}%`)))risks.push(`${Math.round(purchase.chance*100)}% ${t().chance} · −€${purchase.cash}M ${t().cash}`);const known={doping:variant===1?`20% ${t().chance} · −€18M ${t().cash}`:`25% ${t().chance} · −€10M ${t().cash}`,sahte_evrak:`18% ${t().chance} · −1 ${t().trust}`,taraftar:variant===1?`25% ${t().chance} · −1 ${t().trust}`:"",gecici_prim:variant===1?`60% ${t().chance}`:`30% ${t().chance}`};if(known[key]&&!risks.includes(known[key]))risks.push(known[key]);return risks.length?risks.join(" · "):t().none;}
  function costFor(price,meta){const costs=[];if(Number.isFinite(Number(price)))costs.push(Number(price)>0?`€${Math.round(Number(price))}M ${t().price}`:t().none);if(meta){if(meta.chem)costs.push(`−${meta.chem} ${t().chem}`);if(meta.trust)costs.push(`−${meta.trust} ${t().trust}`);if(meta.nextTurn)costs.push(`−€${meta.nextTurn}M · ${t().rounds(meta.turns||1)}`);if(meta.trade)costs.push(`${meta.trade} ${t().burn}`);if(meta.coupon)costs.push(`−€${meta.coupon}M ${t().coupon}`);}return costs.length?costs.join(" · "):t().none;}
  function summary(key,variant=0,context={}){const meta=typeof root.cardCostMeta==="function"?root.cardCostMeta(key,variant):{},power=Number(context.power)||0,source=context.source||t().market;return{key,variant,power,duration:durationFor(key),cost:costFor(context.price,meta),risk:riskFor(key,variant,meta),source:`${source} · ${t().card}`};}
  function render(value){const item=value&&value.key?value:summary(String(value||"")),rows=[[t().power,`${item.power>=0?"+":""}${item.power}`,item.power>=0?"positive":"negative"],[t().duration,item.duration,""],[t().cost,item.cost,"cost"],[t().risk,item.risk,item.risk===t().none?"":"risk"],[t().source,item.source,"source"]];return `<dl class="card-effect-summary">${rows.map(([label,text,tone])=>`<div class="${tone?`is-${tone}`:""}"><dt>${esc(label)}</dt><dd>${esc(text)}</dd></div>`).join("")}</dl>`;}
  root.CopaCardEffectSummary=Object.freeze({summary,render,durationFor,riskFor,costFor});
})(window);
